// Advent of Code - Day 7
//
// Find the root node of a tree. Each node may have an arbitrary number of
// children. All nodes except the root have a parent. Each node also has a
// weight, which we will note for the next puzzle in this pair. We assume
// there are no nodes with the same name.
//

// puzzle input, uniquely generated for each participant
// I should move this to a separate file (did this with day 9)
const list  = [
{ name: 'dsiixv', weight: 52, children: [], parent: '' },
{ name: 'fhimhm', weight: 66, children: [], parent: '' },
{ name: 'mdlubuq', weight: 73, children: [], parent: '' },
{ name: 'ulobwyb', weight: 41, children: [], parent: '' },
{ name: 'cbgnzhz', weight: 70, children: [], parent: '' },
{ name: 'hrheyzf', weight: 946, children: [ 'fixqj', 'msyvs', 'pdwjcd', 'tlgdija'], parent: '' },
{ name: 'yrnjhqc', weight: 31, children: [], parent: '' },
{ name: 'xlglga', weight: 714, children: [ 'hohft', 'funabvw', 'zhxnpoh', 'unpdcwm'], parent: '' },
{ name: 'hcvwov', weight: 240, children: [], parent: '' },
{ name: 'qnhvjec', weight: 35016, children: [ 'pimzjjp', 'ghatw', 'tbakk', 'olgmto', 'qeaqiuq', 'wnmnz', 'aabbf'], parent: '' },
{ name: 'efgdfa', weight: 405, children: [ 'uyedi', 'rxkmf', 'syhipz', 'zozcoqd', 'uwprsvh', 'dqhoh', 'rcbhgw'], parent: '' },
{ name: 'vofrtf', weight: 55, children: [], parent: '' },
{ name: 'gipbso', weight: 52, children: [], parent: '' },
{ name: 'cviwy', weight: 426, children: [ 'ildgly', 'syojg', 'tgoztyw', 'doavm'], parent: '' },
{ name: 'okzkfw', weight: 159, children: [ 'ndteuz', 'bkmepbs'], parent: '' },
{ name: 'ylfvgv', weight: 5, children: [], parent: '' },
{ name: 'ydxuhqe', weight: 72, children: [ 'bfftnj', 'uwrll', 'njlaepf', 'kbfpx'], parent: '' },
{ name: 'hwfcy', weight: 54, children: [], parent: '' },
{ name: 'iqtdzrh', weight: 65, children: [ 'qoppte', 'jcsqqxv'], parent: '' },
{ name: 'ddumyx', weight: 220, children: [ 'yjowio', 'gefjk'], parent: '' },
{ name: 'edagh', weight: 12, children: [], parent: '' },
{ name: 'kefudoj', weight: 82, children: [], parent: '' },
{ name: 'indjoox', weight: 36, children: [], parent: '' },
{ name: 'cliojs', weight: 35, children: [], parent: '' },
{ name: 'lrvmyj', weight: 79, children: [ 'fadkfic', 'pcikcq', 'fgeup'], parent: '' },
{ name: 'mvyzuw', weight: 73, children: [], parent: '' },
{ name: 'nholw', weight: 52, children: [], parent: '' },
{ name: 'sjbqzk', weight: 212, children: [ 'sijon', 'bcedyx'], parent: '' },
{ name: 'majskr', weight: 49, children: [], parent: '' },
{ name: 'qjutng', weight: 15, children: [], parent: '' },
{ name: 'iavwfbb', weight: 19, children: [], parent: '' },
{ name: 'ywonug', weight: 50, children: [ 'dgjyf', 'kobwktw'], parent: '' },
{ name: 'taxky', weight: 77, children: [], parent: '' },
{ name: 'lufkiy', weight: 44, children: [], parent: '' },
{ name: 'lcwqdxx', weight: 34, children: [], parent: '' },
{ name: 'felksho', weight: 204, children: [ 'vkile', 'ihadu', 'qfczh', 'wvgzlw', 'axawjtm', 'eutun', 'vkzmf'], parent: '' },
{ name: 'rvtus', weight: 94, children: [], parent: '' },
{ name: 'zjxjhwc', weight: 53, children: [], parent: '' },
{ name: 'bnmsz', weight: 95, children: [], parent: '' },
{ name: 'cvcyykp', weight: 31, children: [], parent: '' },
{ name: 'bfxvxpl', weight: 35, children: [], parent: '' },
{ name: 'niavkxg', weight: 16, children: [], parent: '' },
{ name: 'zwcsjgs', weight: 7, children: [], parent: '' },
{ name: 'gtqwrrx', weight: 44, children: [], parent: '' },
{ name: 'vszpkfs', weight: 107, children: [ 'rubvop', 'qsvjd'], parent: '' },
{ name: 'axawjtm', weight: 12, children: [ 'gtbocpw', 'oxlvr', 'mvfjras', 'vgyzdkt'], parent: '' },
{ name: 'ulvbf', weight: 82, children: [], parent: '' },
{ name: 'vkzmf', weight: 252, children: [], parent: '' },
{ name: 'jnedlwi', weight: 100, children: [ 'rkftwvy', 'gwyrtw'], parent: '' },
{ name: 'sztry', weight: 247, children: [ 'vddarvs', 'tlzlq'], parent: '' },
{ name: 'anwbrxk', weight: 69, children: [ 'ybnsg', 'rfwgt', 'pcppql'], parent: '' },
{ name: 'pfxoef', weight: 66, children: [], parent: '' },
{ name: 'ghqixh', weight: 171, children: [ 'cjcytbb', 'dmare'], parent: '' },
{ name: 'jwrmi', weight: 130, children: [ 'mhrzazo', 'qeuwgn'], parent: '' },
{ name: 'umsrz', weight: 7, children: [ 'jwrbg', 'wqpahuv', 'zquvn', 'sfjyf', 'uebmnqa', 'qqkqhzb', 'gmbup'], parent: '' },
{ name: 'wtsqx', weight: 46, children: [], parent: '' },
{ name: 'rzldn', weight: 31, children: [], parent: '' },
{ name: 'usmtdk', weight: 166, children: [ 'pikelbw', 'edwlns'], parent: '' },
{ name: 'pyhecs', weight: 59, children: [], parent: '' },
{ name: 'shwsf', weight: 56, children: [ 'wtbst', 'ryjqaz'], parent: '' },
{ name: 'jhkkrg', weight: 63, children: [], parent: '' },
{ name: 'eaagt', weight: 40, children: [], parent: '' },
{ name: 'wkbqm', weight: 59, children: [], parent: '' },
{ name: 'iivwxhd', weight: 150, children: [ 'yfgyi', 'grdimrp'], parent: '' },
{ name: 'nlkwsrn', weight: 50, children: [], parent: '' },
{ name: 'idnsypp', weight: 94, children: [], parent: '' },
{ name: 'aixwgk', weight: 41, children: [], parent: '' },
{ name: 'yhhnavm', weight: 84, children: [], parent: '' },
{ name: 'lngdxkd', weight: 146, children: [ 'hkkzpzh', 'ihvfxeo'], parent: '' },
{ name: 'dkwwoa', weight: 73, children: [ 'sntbr', 'xbywgft', 'xlkvx', 'akght'], parent: '' },
{ name: 'jevqne', weight: 8, children: [], parent: '' },
{ name: 'vurnn', weight: 81, children: [ 'fkehyrg', 'qhktzou'], parent: '' },
{ name: 'ngoog', weight: 20, children: [ 'uusec', 'rrnkqx', 'jafsqqu', 'ryeiot'], parent: '' },
{ name: 'hxhguzh', weight: 75, children: [], parent: '' },
{ name: 'kohxzh', weight: 1765, children: [ 'mjpmw', 'cbmkr', 'vmofl', 'wsjizsy', 'redeub'], parent: '' },
{ name: 'twpvnu', weight: 56, children: [], parent: '' },
{ name: 'kzumm', weight: 132, children: [ 'czgxag', 'vytlfm', 'qowepn'], parent: '' },
{ name: 'fgnye', weight: 44, children: [ 'pxcjw', 'bnmuprs'], parent: '' },
{ name: 'jvqfj', weight: 60, children: [], parent: '' },
{ name: 'yvllxxw', weight: 55, children: [], parent: '' },
{ name: 'hsmaze', weight: 34, children: [ 'fxzqvoh', 'fcvsqp', 'okzkfw', 'vwtsdsf', 'ipbbnp', 'txdprek'], parent: '' },
{ name: 'aujdy', weight: 14, children: [], parent: '' },
{ name: 'yjcevge', weight: 61, children: [ 'rpyxxhm', 'tfbqaoe'], parent: '' },
{ name: 'blcpm', weight: 217, children: [ 'qibrsjj', 'wcfykko'], parent: '' },
{ name: 'pfltnc', weight: 44, children: [], parent: '' },
{ name: 'anqas', weight: 63, children: [ 'riuwg', 'jhkkrg'], parent: '' },
{ name: 'rtseps', weight: 51, children: [], parent: '' },
{ name: 'vmkfcpw', weight: 92, children: [], parent: '' },
{ name: 'pcppql', weight: 78, children: [], parent: '' },
{ name: 'tqrqs', weight: 43, children: [], parent: '' },
{ name: 'syxdt', weight: 12, children: [], parent: '' },
{ name: 'ejlecie', weight: 79, children: [], parent: '' },
{ name: 'xpdmegi', weight: 16, children: [], parent: '' },
{ name: 'dgjyf', weight: 62, children: [], parent: '' },
{ name: 'uxhpm', weight: 51, children: [], parent: '' },
{ name: 'znchnta', weight: 66, children: [ 'sutzt', 'kvjyw', 'hlshpkq', 'corcne', 'rflrj', 'yhadh', 'ouypz'], parent: '' },
{ name: 'zmdvl', weight: 50, children: [], parent: '' },
{ name: 'fixysjm', weight: 1386, children: [ 'zjylql', 'ytadaxm', 'fgnye'], parent: '' },
{ name: 'yevywe', weight: 63, children: [ 'qeayjnt', 'ixyeq', 'hgaoiz', 'rcfaaml', 'zuzhmf'], parent: '' },
{ name: 'rxkmf', weight: 811, children: [ 'yedvssr', 'xvwgxm', 'wfeurd'], parent: '' },
{ name: 'mcmzs', weight: 53, children: [], parent: '' },
{ name: 'vsmdkp', weight: 60, children: [], parent: '' },
{ name: 'oyurf', weight: 27, children: [ 'zhjtcdl', 'jswxshd', 'hfwpcsa', 'lbvfwz', 'obolmhh', 'grgkv'], parent: '' },
{ name: 'yawmlbb', weight: 191, children: [ 'iavwfbb', 'xjjvneg'], parent: '' },
{ name: 'fblsn', weight: 44, children: [], parent: '' },
{ name: 'doavm', weight: 223, children: [ 'drasjw', 'cwwwcge'], parent: '' },
{ name: 'udyivld', weight: 18, children: [ 'osrdt', 'jpyojky', 'vhnnnv', 'gyxqc'], parent: '' },
{ name: 'ddqnllo', weight: 167, children: [ 'cdfij', 'quohxia'], parent: '' },
{ name: 'bwbym', weight: 55, children: [], parent: '' },
{ name: 'ufpdyq', weight: 22, children: [], parent: '' },
{ name: 'hkjcnv', weight: 73, children: [ 'nderndc', 'owjtoo'], parent: '' },
{ name: 'ndhravs', weight: 10, children: [], parent: '' },
{ name: 'qjkkohe', weight: 25, children: [], parent: '' },
{ name: 'jrott', weight: 44, children: [ 'jgylf', 'kaitdu'], parent: '' },
{ name: 'unvqq', weight: 173, children: [ 'lxdji', 'ldkojcj'], parent: '' },
{ name: 'zrgqfb', weight: 81, children: [], parent: '' },
{ name: 'csbgxs', weight: 29, children: [], parent: '' },
{ name: 'qeaqiuq', weight: 1106, children: [ 'nwlkk', 'ytyhmux', 'nxmtm', 'izpta'], parent: '' },
{ name: 'rqeftjw', weight: 51, children: [], parent: '' },
{ name: 'tbakbq', weight: 62, children: [], parent: '' },
{ name: 'vnhhu', weight: 62, children: [], parent: '' },
{ name: 'grgkv', weight: 85, children: [ 'xgmrufk', 'cvvkno'], parent: '' },
{ name: 'pggrr', weight: 29, children: [ 'bttvl', 'zrmzpo', 'upatvy'], parent: '' },
{ name: 'zumdwwu', weight: 43, children: [ 'jfssr', 'aujdy', 'adkyx', 'mragx'], parent: '' },
{ name: 'euxvn', weight: 105, children: [ 'qtazfdw', 'uzarat', 'mikalda'], parent: '' },
{ name: 'tpbcg', weight: 98, children: [], parent: '' },
{ name: 'kdnwlnz', weight: 36, children: [], parent: '' },
{ name: 'pncda', weight: 183, children: [ 'uswszht', 'zeebqts'], parent: '' },
{ name: 'zlvjnx', weight: 130, children: [ 'vctupmx', 'gmxdpc'], parent: '' },
{ name: 'iljdm', weight: 203, children: [ 'emqwt', 'leknm'], parent: '' },
{ name: 'lmgxknk', weight: 49, children: [], parent: '' },
{ name: 'pikelbw', weight: 34, children: [], parent: '' },
{ name: 'kqqegw', weight: 89, children: [], parent: '' },
{ name: 'eigsdc', weight: 20, children: [], parent: '' },
{ name: 'qbhvu', weight: 94, children: [], parent: '' },
{ name: 'kqoae', weight: 61, children: [ 'tqrqs', 'bfozr', 'kkqeg'], parent: '' },
{ name: 'bozfw', weight: 5, children: [], parent: '' },
{ name: 'silwwua', weight: 20867, children: [ 'kzocw', 'ymhsa', 'mzcebu'], parent: '' },
{ name: 'fcxninx', weight: 473, children: [ 'pmxzfd', 'kbvzpv', 'zskam', 'oyurf'], parent: '' },
{ name: 'ihvfxeo', weight: 14, children: [], parent: '' },
{ name: 'rkftwvy', weight: 52, children: [], parent: '' },
{ name: 'kccra', weight: 26, children: [], parent: '' },
{ name: 'vkxbeox', weight: 353, children: [], parent: '' },
{ name: 'suiagk', weight: 59, children: [], parent: '' },
{ name: 'lnqzgti', weight: 60, children: [], parent: '' },
{ name: 'leknm', weight: 50, children: [], parent: '' },
{ name: 'yxvmxzg', weight: 35, children: [], parent: '' },
{ name: 'jezubi', weight: 54, children: [ 'lnqzgti', 'hvsiuf'], parent: '' },
{ name: 'bzqhk', weight: 33, children: [ 'ndmpgss', 'kcoayj'], parent: '' },
{ name: 'xaovjvs', weight: 74, children: [], parent: '' },
{ name: 'mjuyo', weight: 263, children: [ 'psrup', 'boeuyxx'], parent: '' },
{ name: 'tvoptyn', weight: 1776, children: [ 'xjbtfms', 'tiphry'], parent: '' },
{ name: 'jbhohbx', weight: 25, children: [], parent: '' },
{ name: 'kqfgnql', weight: 22, children: [ 'pmozz', 'hspqr', 'ydxuhqe', 'txhxoib', 'cncoep', 'ripidvx', 'qezvrjl'], parent: '' },
{ name: 'pdkfixk', weight: 22, children: [], parent: '' },
{ name: 'kxzwel', weight: 80, children: [], parent: '' },
{ name: 'sykmuwo', weight: 243, children: [ 'zvogn', 'esmbu'], parent: '' },
{ name: 'livul', weight: 40, children: [], parent: '' },
{ name: 'rvmntl', weight: 346, children: [], parent: '' },
{ name: 'xqztuq', weight: 24, children: [ 'pyhecs', 'jqgkz', 'bsythck', 'ranlxct'], parent: '' },
{ name: 'edyohkw', weight: 79, children: [], parent: '' },
{ name: 'hszzxp', weight: 64, children: [ 'xcdswr', 'oukuy'], parent: '' },
{ name: 'yfgyi', weight: 56, children: [], parent: '' },
{ name: 'pmozz', weight: 74, children: [ 'ngaawt', 'oaknu', 'cgbkrnc'], parent: '' },
{ name: 'tfglbeh', weight: 56, children: [], parent: '' },
{ name: 'wpvozgo', weight: 53, children: [], parent: '' },
{ name: 'njaig', weight: 77, children: [], parent: '' },
{ name: 'jwrbg', weight: 134, children: [ 'fymyi', 'utpyp', 'ulxscm', 'cliojs'], parent: '' },
{ name: 'olnfe', weight: 33, children: [], parent: '' },
{ name: 'jcsqqxv', weight: 52, children: [], parent: '' },
{ name: 'fvkew', weight: 21, children: [], parent: '' },
{ name: 'nkdbmjv', weight: 34, children: [], parent: '' },
{ name: 'fhjgv', weight: 55, children: [], parent: '' },
{ name: 'tvqlaw', weight: 14, children: [], parent: '' },
{ name: 'wqpahuv', weight: 274, children: [], parent: '' },
{ name: 'myoyl', weight: 82, children: [], parent: '' },
{ name: 'pjzcs', weight: 38, children: [], parent: '' },
{ name: 'pcehxbx', weight: 1859, children: [ 'hlfmvdt', 'ngoog', 'mwhraq'], parent: '' },
{ name: 'kqohkg', weight: 56, children: [ 'hezkdc', 'kgfudu', 'omeew'], parent: '' },
{ name: 'adtpk', weight: 1655, children: [ 'unvqq', 'bpbwl', 'anqas', 'kmnzz'], parent: '' },
{ name: 'afihdk', weight: 65, children: [], parent: '' },
{ name: 'rtiaapt', weight: 18, children: [], parent: '' },
{ name: 'obolmhh', weight: 109, children: [ 'lufkiy', 'kiryhz'], parent: '' },
{ name: 'dkegbrt', weight: 45, children: [], parent: '' },
{ name: 'rbiarxk', weight: 81, children: [ 'erngeah', 'cqcjys', 'bxjqibv'], parent: '' },
{ name: 'hmrzqlh', weight: 87, children: [], parent: '' },
{ name: 'biemun', weight: 295, children: [ 'ejbtu', 'hszzxp', 'kcxiq', 'khixwdd', 'usmtdk'], parent: '' },
{ name: 'mvfjras', weight: 60, children: [], parent: '' },
{ name: 'uqktn', weight: 246, children: [ 'gtqwrrx', 'qtshuo'], parent: '' },
{ name: 'kmpmdb', weight: 8, children: [], parent: '' },
{ name: 'lylxk', weight: 22, children: [], parent: '' },
{ name: 'nxmtm', weight: 84, children: [], parent: '' },
{ name: 'goapac', weight: 88, children: [], parent: '' },
{ name: 'zlxlwv', weight: 43, children: [], parent: '' },
{ name: 'nirov', weight: 74, children: [], parent: '' },
{ name: 'fcjjqev', weight: 78, children: [], parent: '' },
{ name: 'finxtiu', weight: 92, children: [ 'vgdsszs', 'gofjvi', 'mxpvph'], parent: '' },
{ name: 'uvpwrf', weight: 73, children: [], parent: '' },
{ name: 'vgnkq', weight: 104, children: [ 'jczkx', 'iydqii'], parent: '' },
{ name: 'gsbmh', weight: 84, children: [], parent: '' },
{ name: 'ssblis', weight: 86, children: [], parent: '' },
{ name: 'knvxq', weight: 1845, children: [ 'pvbgvb', 'mcghosj', 'qocnylk'], parent: '' },
{ name: 'kvjyw', weight: 57, children: [ 'livul', 'eaagt', 'rukzsa', 'gsdzpjh'], parent: '' },
{ name: 'zhpdhat', weight: 76, children: [], parent: '' },
{ name: 'ypjnmr', weight: 39, children: [], parent: '' },
{ name: 'yauryvu', weight: 97, children: [], parent: '' },
{ name: 'ucahbv', weight: 82, children: [], parent: '' },
{ name: 'rkswk', weight: 70, children: [ 'kccra', 'lqasevp', 'bdvtnul', 'swqres'], parent: '' },
{ name: 'bqvtbsr', weight: 39, children: [], parent: '' },
{ name: 'cmfcqh', weight: 149, children: [ 'wlwnand', 'zikmmr'], parent: '' },
{ name: 'ouypz', weight: 67, children: [ 'mxelfv', 'fogmaih'], parent: '' },
{ name: 'nlrbcxx', weight: 41, children: [], parent: '' },
{ name: 'mrmuat', weight: 21, children: [], parent: '' },
{ name: 'kcxiq', weight: 150, children: [ 'mdvnu', 'dcwcs'], parent: '' },
{ name: 'aabbf', weight: 881, children: [ 'dsoyvp', 'hwraaxu', 'lrvmyj'], parent: '' },
{ name: 'mjxfsc', weight: 53, children: [], parent: '' },
{ name: 'dmare', weight: 55, children: [], parent: '' },
{ name: 'iruee', weight: 89, children: [], parent: '' },
{ name: 'gpsnzs', weight: 76, children: [], parent: '' },
{ name: 'wnpkwy', weight: 27, children: [], parent: '' },
{ name: 'zvnzep', weight: 174, children: [ 'tvqlaw', 'aufxtq'], parent: '' },
{ name: 'yysyjbk', weight: 1630, children: [ 'wpvozgo', 'mjxfsc', 'iality', 'vwupkmh'], parent: '' },
{ name: 'cgbkrnc', weight: 62, children: [], parent: '' },
{ name: 'mnfknb', weight: 41, children: [], parent: '' },
{ name: 'kcoayj', weight: 89, children: [], parent: '' },
{ name: 'vybmch', weight: 79, children: [ 'ebyfpmf', 'dnqdmxc'], parent: '' },
{ name: 'lmrzi', weight: 87, children: [], parent: '' },
{ name: 'tiyvea', weight: 30, children: [], parent: '' },
{ name: 'pcikcq', weight: 36, children: [], parent: '' },
{ name: 'mlqoz', weight: 20, children: [], parent: '' },
{ name: 'brmvw', weight: 144, children: [ 'qjutng', 'janbnmh'], parent: '' },
{ name: 'zgkxkj', weight: 72, children: [ 'bwrpc', 'wntfmtn', 'hwjmzs', 'vkxbeox'], parent: '' },
{ name: 'gzcbv', weight: 54, children: [], parent: '' },
{ name: 'nsqpaq', weight: 55, children: [], parent: '' },
{ name: 'hohft', weight: 69, children: [ 'hfjtksr', 'efzjseb', 'ypjnmr', 'bqvtbsr'], parent: '' },
{ name: 'kkqeg', weight: 43, children: [], parent: '' },
{ name: 'gafjq', weight: 74, children: [], parent: '' },
{ name: 'haano', weight: 296, children: [ 'rlburl', 'njkvleo'], parent: '' },
{ name: 'tvbmh', weight: 99, children: [], parent: '' },
{ name: 'fvsitx', weight: 212, children: [ 'nsvwcl', 'hohrape'], parent: '' },
{ name: 'yhtpdwu', weight: 71, children: [], parent: '' },
{ name: 'qxsjs', weight: 95, children: [], parent: '' },
{ name: 'qseqsgt', weight: 22, children: [], parent: '' },
{ name: 'vkhdfmv', weight: 36, children: [], parent: '' },
{ name: 'ikicwez', weight: 69, children: [], parent: '' },
{ name: 'tdrdq', weight: 24, children: [], parent: '' },
{ name: 'bgudw', weight: 94, children: [], parent: '' },
{ name: 'zhjtcdl', weight: 134, children: [ 'ceutto', 'fhynmi', 'qmyohe'], parent: '' },
{ name: 'pavtnxe', weight: 38, children: [], parent: '' },
{ name: 'xvoehjz', weight: 301, children: [ 'zznjih', 'wseim'], parent: '' },
{ name: 'klfyu', weight: 40, children: [], parent: '' },
{ name: 'zhxnpoh', weight: 119, children: [ 'ltyxiwk', 'wkgouh'], parent: '' },
{ name: 'bezoxx', weight: 184, children: [ 'afihdk', 'jevfpj'], parent: '' },
{ name: 'ivldghm', weight: 64, children: [ 'enmxpmj', 'wsrrryh'], parent: '' },
{ name: 'osnpbou', weight: 111, children: [ 'zpuktmx', 'itlno'], parent: '' },
{ name: 'uofuvf', weight: 70, children: [], parent: '' },
{ name: 'mgvcyl', weight: 51, children: [ 'nsqpaq', 'fhjgv'], parent: '' },
{ name: 'lluabej', weight: 97, children: [], parent: '' },
{ name: 'hwjmzs', weight: 273, children: [ 'agsfbkx', 'znswber'], parent: '' },
{ name: 'udlhalx', weight: 26, children: [], parent: '' },
{ name: 'gewlsr', weight: 476, children: [ 'uqktn', 'nknpwkc', 'udyivld'], parent: '' },
{ name: 'fsjvyxv', weight: 27, children: [], parent: '' },
{ name: 'birtjxh', weight: 78, children: [], parent: '' },
{ name: 'eplltu', weight: 84, children: [], parent: '' },
{ name: 'sdixs', weight: 54, children: [], parent: '' },
{ name: 'kqdseyh', weight: 46, children: [], parent: '' },
{ name: 'lfrfa', weight: 76, children: [ 'ejlecie', 'mvxud', 'wgevvca', 'carfsnj'], parent: '' },
{ name: 'lbwgsap', weight: 33, children: [ 'gpsnzs', 'santsu'], parent: '' },
{ name: 'pnjtt', weight: 45, children: [], parent: '' },
{ name: 'rcfaaml', weight: 157, children: [ 'avemxf', 'ehwcxy'], parent: '' },
{ name: 'tbutks', weight: 36, children: [], parent: '' },
{ name: 'xmhdsio', weight: 91, children: [], parent: '' },
{ name: 'byjcsn', weight: 51, children: [], parent: '' },
{ name: 'amslmyk', weight: 96, children: [], parent: '' },
{ name: 'jtdvzj', weight: 62, children: [], parent: '' },
{ name: 'xnaam', weight: 88, children: [ 'lylxk', 'sybcl', 'kuqsuy'], parent: '' },
{ name: 'boeuyxx', weight: 53, children: [], parent: '' },
{ name: 'pxcwhq', weight: 30, children: [], parent: '' },
{ name: 'mckyvtt', weight: 52, children: [], parent: '' },
{ name: 'pctkyat', weight: 25, children: [], parent: '' },
{ name: 'lomxh', weight: 53, children: [], parent: '' },
{ name: 'ltccbob', weight: 297, children: [ 'ndhravs', 'qlryl'], parent: '' },
{ name: 'vgyzdkt', weight: 60, children: [], parent: '' },
{ name: 'pyzbqz', weight: 74, children: [], parent: '' },
{ name: 'cjkieim', weight: 519, children: [ 'myeecwt', 'agtab', 'rhtqj', 'mmriyf', 'mfcutqz'], parent: '' },
{ name: 'ducdc', weight: 41, children: [], parent: '' },
{ name: 'mnxoac', weight: 30, children: [], parent: '' },
{ name: 'umtmwow', weight: 30, children: [], parent: '' },
{ name: 'qsxqwub', weight: 94, children: [ 'klfyu', 'mlzfw'], parent: '' },
{ name: 'pdwjcd', weight: 105, children: [ 'vcoszdq', 'fkmpv'], parent: '' },
{ name: 'wifaf', weight: 41, children: [ 'dnunil', 'gafjq', 'gwgchq'], parent: '' },
{ name: 'tpabsyz', weight: 91, children: [], parent: '' },
{ name: 'uwrll', weight: 47, children: [], parent: '' },
{ name: 'dcjiqny', weight: 1371, children: [ 'npblyaq', 'qeoetnp', 'qoeviy'], parent: '' },
{ name: 'rlburl', weight: 9, children: [], parent: '' },
{ name: 'itlno', weight: 37, children: [], parent: '' },
{ name: 'ehpdfno', weight: 285, children: [ 'bcrso', 'jqwaifx'], parent: '' },
{ name: 'njkvleo', weight: 9, children: [], parent: '' },
{ name: 'uswszht', weight: 24, children: [], parent: '' },
{ name: 'qvpou', weight: 180, children: [ 'sndject', 'bzmhwwo'], parent: '' },
{ name: 'ngaawt', weight: 62, children: [], parent: '' },
{ name: 'kyhezqn', weight: 45, children: [], parent: '' },
{ name: 'arouwsi', weight: 59, children: [], parent: '' },
{ name: 'uyoez', weight: 99, children: [], parent: '' },
{ name: 'quoqibc', weight: 195, children: [ 'znuldtj', 'bljppq'], parent: '' },
{ name: 'tiphry', weight: 33, children: [], parent: '' },
{ name: 'lbvfwz', weight: 89, children: [ 'qypsl', 'gzcbv'], parent: '' },
{ name: 'bzmhwwo', weight: 5, children: [], parent: '' },
{ name: 'tcbxnrf', weight: 285, children: [ 'ybgdelp', 'aqrpio'], parent: '' },
{ name: 'arjgn', weight: 392, children: [], parent: '' },
{ name: 'qfczh', weight: 218, children: [ 'ivhtlxa', 'jdazgj'], parent: '' },
{ name: 'jpyojky', weight: 79, children: [], parent: '' },
{ name: 'zinjsj', weight: 30, children: [], parent: '' },
{ name: 'qfsmgqe', weight: 982, children: [ 'mgvcyl', 'cekchxh', 'qnscg'], parent: '' },
{ name: 'mlzfw', weight: 40, children: [], parent: '' },
{ name: 'ulszlax', weight: 42, children: [], parent: '' },
{ name: 'myeecwt', weight: 69, children: [ 'veiljb', 'wydtqax', 'pnjtt', 'sxwbzyj'], parent: '' },
{ name: 'vkuucpv', weight: 260, children: [ 'fenymdp', 'uwehdau'], parent: '' },
{ name: 'qezvrjl', weight: 212, children: [ 'jdqhjk', 'htwzu', 'lzevbng'], parent: '' },
{ name: 'qnscg', weight: 161, children: [], parent: '' },
{ name: 'wkkkv', weight: 11, children: [], parent: '' },
{ name: 'bpbwl', weight: 149, children: [ 'mlqoz', 'miwjfr'], parent: '' },
{ name: 'icspwbg', weight: 83, children: [ 'iljdm', 'sztry', 'anwbrxk', 'ddqnllo', 'gtbmrcp', 'cpzwgk'], parent: '' },
{ name: 'bddlvs', weight: 70, children: [], parent: '' },
{ name: 'mragx', weight: 14, children: [], parent: '' },
{ name: 'vdyhna', weight: 166, children: [ 'glori', 'azttml', 'jxraf'], parent: '' },
{ name: 'zjylql', weight: 78, children: [ 'fsoqc', 'hefjuue'], parent: '' },
{ name: 'jdqhjk', weight: 16, children: [], parent: '' },
{ name: 'etkzf', weight: 11, children: [], parent: '' },
{ name: 'grdimrp', weight: 56, children: [], parent: '' },
{ name: 'tlics', weight: 101, children: [ 'twpvnu', 'tfglbeh'], parent: '' },
{ name: 'kskkjn', weight: 1081, children: [ 'uxmjgh', 'kqoae', 'wswwck', 'zwymlsj', 'qvpou', 'mtxzek', 'elxccty'], parent: '' },
{ name: 'qsvjd', weight: 31, children: [], parent: '' },
{ name: 'uurqa', weight: 33, children: [], parent: '' },
{ name: 'gytzi', weight: 18, children: [], parent: '' },
{ name: 'xsvage', weight: 27, children: [], parent: '' },
{ name: 'gefjk', weight: 21, children: [], parent: '' },
{ name: 'vpbec', weight: 263, children: [], parent: '' },
{ name: 'mocpa', weight: 79, children: [ 'ldvcrw', 'atxfply', 'ogtxa', 'rbbkdj', 'blcpm'], parent: '' },
{ name: 'wsdqchf', weight: 71, children: [], parent: '' },
{ name: 'zznjih', weight: 11, children: [], parent: '' },
{ name: 'ryjqaz', weight: 73, children: [], parent: '' },
{ name: 'hspqr', weight: 66, children: [ 'hjxzwnq', 'ojrixty'], parent: '' },
{ name: 'phkzo', weight: 263, children: [ 'licst', 'nbkzscx'], parent: '' },
{ name: 'haayebg', weight: 39, children: [ 'ogziig', 'pyscsi'], parent: '' },
{ name: 'kbdnbnd', weight: 94, children: [], parent: '' },
{ name: 'ioyealn', weight: 51, children: [], parent: '' },
{ name: 'nuoic', weight: 20, children: [ 'pmssap', 'bzuago', 'tvbmh'], parent: '' },
{ name: 'kuqsuy', weight: 22, children: [], parent: '' },
{ name: 'hvsiuf', weight: 60, children: [], parent: '' },
{ name: 'werskvv', weight: 78, children: [], parent: '' },
{ name: 'hohrape', weight: 90, children: [], parent: '' },
{ name: 'sybcl', weight: 22, children: [], parent: '' },
{ name: 'ksnxlcl', weight: 117, children: [ 'sdjxpp', 'yzpyzu', 'ulobwyb', 'afbnq'], parent: '' },
{ name: 'qlchz', weight: 5277, children: [ 'doxfeq', 'luiiv', 'hsmaze'], parent: '' },
{ name: 'ihadu', weight: 144, children: [ 'dquqam', 'ctvrea'], parent: '' },
{ name: 'dquqam', weight: 54, children: [], parent: '' },
{ name: 'pjamo', weight: 113, children: [ 'vnhhu', 'jtdvzj'], parent: '' },
{ name: 'xeypnpr', weight: 183, children: [ 'qiund', 'kdnwlnz'], parent: '' },
{ name: 'loaft', weight: 59, children: [], parent: '' },
{ name: 'loykzr', weight: 16, children: [], parent: '' },
{ name: 'bsbsdiu', weight: 81, children: [ 'ssmhkwq', 'alolk'], parent: '' },
{ name: 'efzjseb', weight: 39, children: [], parent: '' },
{ name: 'lbkrk', weight: 17, children: [], parent: '' },
{ name: 'ipbbnp', weight: 127, children: [ 'iauetan', 'tbakbq'], parent: '' },
{ name: 'uilvahq', weight: 1076, children: [ 'oztxjfl', 'oiufrau', 'ewyrp'], parent: '' },
{ name: 'gmbup', weight: 274, children: [], parent: '' },
{ name: 'gldvef', weight: 18, children: [], parent: '' },
{ name: 'evvfcyi', weight: 13, children: [], parent: '' },
{ name: 'nbhdty', weight: 97, children: [], parent: '' },
{ name: 'ncbrxsy', weight: 15, children: [], parent: '' },
{ name: 'dnunil', weight: 74, children: [], parent: '' },
{ name: 'zcggn', weight: 56, children: [], parent: '' },
{ name: 'mbcwjt', weight: 225, children: [ 'wxyaqte', 'kpffozq'], parent: '' },
{ name: 'vgkjgy', weight: 16, children: [], parent: '' },
{ name: 'bcnqhw', weight: 298, children: [ 'ohqivu', 'jzwusi', 'jzcstbe', 'xayqwyj', 'kmwkft'], parent: '' },
{ name: 'gyxqc', weight: 79, children: [], parent: '' },
{ name: 'ripidvx', weight: 148, children: [ 'rergyy', 'rwhjmp'], parent: '' },
{ name: 'mxpvph', weight: 67, children: [], parent: '' },
{ name: 'iauetan', weight: 62, children: [], parent: '' },
{ name: 'voawog', weight: 34, children: [], parent: '' },
{ name: 'mzcebu', weight: 11, children: [ 'rlgrkq', 'xlglga', 'hrheyzf', 'gbwfjf', 'mhkrny'], parent: '' },
{ name: 'sexuv', weight: 92, children: [ 'ednlrw', 'zcggn'], parent: '' },
{ name: 'fezoyaj', weight: 78, children: [], parent: '' },
{ name: 'uxmjgh', weight: 70, children: [ 'mnxoac', 'pxcwhq', 'ytjheqk', 'tmtfhr'], parent: '' },
{ name: 'tvfptpz', weight: 73, children: [], parent: '' },
{ name: 'rywggm', weight: 78, children: [ 'gxuovng', 'ragcph', 'epstabj'], parent: '' },
{ name: 'ymhsa', weight: 7457, children: [ 'zzqtmxd', 'yfwwrkp', 'yahzcyp', 'hmugaom'], parent: '' },
{ name: 'ygvvvq', weight: 392, children: [], parent: '' },
{ name: 'izssdb', weight: 215, children: [ 'ycseeag', 'ytzdrvj'], parent: '' },
{ name: 'bttvl', weight: 95, children: [], parent: '' },
{ name: 'abjmd', weight: 30, children: [], parent: '' },
{ name: 'mspxpr', weight: 1837, children: [ 'fvhvq', 'guvto'], parent: '' },
{ name: 'enogehk', weight: 45, children: [], parent: '' },
{ name: 'cqcjys', weight: 44, children: [], parent: '' },
{ name: 'rfllomn', weight: 107, children: [ 'lqndkq', 'tzkgrjf', 'lcius', 'lhlgijf'], parent: '' },
{ name: 'wvdswpz', weight: 34, children: [], parent: '' },
{ name: 'ocqrpkf', weight: 46, children: [], parent: '' },
{ name: 'oaknu', weight: 62, children: [], parent: '' },
{ name: 'qvrtwdt', weight: 1289, children: [ 'jnedlwi', 'sexuv', 'vcauqo'], parent: '' },
{ name: 'prnno', weight: 95, children: [], parent: '' },
{ name: 'wgjst', weight: 177, children: [ 'bozfw', 'salxel', 'jrrhzc'], parent: '' },
{ name: 'teapi', weight: 35, children: [], parent: '' },
{ name: 'adkyx', weight: 14, children: [], parent: '' },
{ name: 'huxtvqc', weight: 16, children: [], parent: '' },
{ name: 'mznsk', weight: 11, children: [], parent: '' },
{ name: 'fcvsqp', weight: 183, children: [ 'ebjgfh', 'bnvjfq'], parent: '' },
{ name: 'iwkotv', weight: 89, children: [], parent: '' },
{ name: 'mkykc', weight: 90, children: [], parent: '' },
{ name: 'dlrznye', weight: 83, children: [], parent: '' },
{ name: 'gtxdtf', weight: 42, children: [], parent: '' },
{ name: 'ahism', weight: 144, children: [ 'gkitfsr', 'osbndxb', 'zielffk'], parent: '' },
{ name: 'znztzxd', weight: 29183, children: [ 'jcsjaxj', 'hrwtz', 'fcxninx'], parent: '' },
{ name: 'jsbug', weight: 85, children: [], parent: '' },
{ name: 'kfkhxg', weight: 51, children: [], parent: '' },
{ name: 'tcpvyfj', weight: 18, children: [], parent: '' },
{ name: 'fpdoney', weight: 16, children: [], parent: '' },
{ name: 'kfefhun', weight: 27, children: [], parent: '' },
{ name: 'iufvcm', weight: 38, children: [ 'xjejd', 'goapac'], parent: '' },
{ name: 'fzltz', weight: 8, children: [], parent: '' },
{ name: 'rukzsa', weight: 40, children: [], parent: '' },
{ name: 'doxfeq', weight: 154, children: [ 'kzumm', 'vurnn', 'fzbwmsz', 'bsbsdiu', 'pncda', 'rtromur'], parent: '' },
{ name: 'dfrzb', weight: 53, children: [], parent: '' },
{ name: 'rpbeiqg', weight: 170, children: [ 'qseqsgt', 'qmeawpu'], parent: '' },
{ name: 'ycseeag', weight: 28, children: [], parent: '' },
{ name: 'blfinsi', weight: 52, children: [], parent: '' },
{ name: 'kvsprca', weight: 65, children: [], parent: '' },
{ name: 'uzarat', weight: 35, children: [], parent: '' },
{ name: 'zzlocxd', weight: 62, children: [], parent: '' },
{ name: 'iality', weight: 53, children: [], parent: '' },
{ name: 'daxbf', weight: 805, children: [ 'iktev', 'xqztuq', 'bsvoy'], parent: '' },
{ name: 'hfjpir', weight: 19, children: [], parent: '' },
{ name: 'bsiwtqq', weight: 58, children: [], parent: '' },
{ name: 'qnepf', weight: 88, children: [], parent: '' },
{ name: 'dasmiiw', weight: 56, children: [], parent: '' },
{ name: 'wseim', weight: 11, children: [], parent: '' },
{ name: 'lvgrmfu', weight: 180, children: [ 'ngiol', 'iwidsj'], parent: '' },
{ name: 'nsoju', weight: 38, children: [], parent: '' },
{ name: 'zqaxyz', weight: 59, children: [], parent: '' },
{ name: 'qocnylk', weight: 41, children: [], parent: '' },
{ name: 'fhynmi', weight: 21, children: [], parent: '' },
{ name: 'xeege', weight: 12, children: [], parent: '' },
{ name: 'mfslhp', weight: 95, children: [], parent: '' },
{ name: 'alolk', weight: 75, children: [], parent: '' },
{ name: 'qtazfdw', weight: 35, children: [], parent: '' },
{ name: 'sijon', weight: 37, children: [], parent: '' },
{ name: 'zzpevgd', weight: 17, children: [ 'smqtcaj', 'emxwr', 'uezxhid', 'blvyrzh', 'lvgrmfu', 'vkuucpv', 'eivaf'], parent: '' },
{ name: 'glori', weight: 15, children: [], parent: '' },
{ name: 'ssmhkwq', weight: 75, children: [], parent: '' },
{ name: 'dmkhzgg', weight: 149, children: [ 'fuwekd', 'bwbym'], parent: '' },
{ name: 'xqrrpu', weight: 29, children: [], parent: '' },
{ name: 'yjowio', weight: 21, children: [], parent: '' },
{ name: 'mhrzazo', weight: 36, children: [], parent: '' },
{ name: 'jakmbx', weight: 39, children: [ 'egyfwny', 'khdzsr'], parent: '' },
{ name: 'qzgdlb', weight: 33, children: [], parent: '' },
{ name: 'lwysj', weight: 49, children: [], parent: '' },
{ name: 'czgxag', weight: 33, children: [], parent: '' },
{ name: 'drasjw', weight: 20, children: [], parent: '' },
{ name: 'pxcjw', weight: 41, children: [], parent: '' },
{ name: 'hwfzj', weight: 321, children: [], parent: '' },
{ name: 'ssxqkhq', weight: 67, children: [], parent: '' },
{ name: 'ndteuz', weight: 46, children: [], parent: '' },
{ name: 'rwhjmp', weight: 56, children: [], parent: '' },
{ name: 'xsuxhbq', weight: 1268, children: [ 'injlqnw', 'vdyhna', 'bzqhk'], parent: '' },
{ name: 'aufxtq', weight: 14, children: [], parent: '' },
{ name: 'nknpwkc', weight: 164, children: [ 'pwyfdan', 'jsbug'], parent: '' },
{ name: 'dqhoh', weight: 787, children: [ 'xeypnpr', 'quoqibc', 'wisdd'], parent: '' },
{ name: 'lqndkq', weight: 54, children: [], parent: '' },
{ name: 'vabii', weight: 89, children: [], parent: '' },
{ name: 'pmxzfd', weight: 747, children: [ 'xnaam', 'iaoxdmm', 'hsywhj'], parent: '' },
{ name: 'fuexyx', weight: 8, children: [], parent: '' },
{ name: 'wkxyxtf', weight: 20, children: [], parent: '' },
{ name: 'bfftnj', weight: 47, children: [], parent: '' },
{ name: 'hoqti', weight: 6514, children: [ 'jviven', 'znchnta', 'daxbf'], parent: '' },
{ name: 'aqrpio', weight: 24, children: [], parent: '' },
{ name: 'otsyp', weight: 54, children: [], parent: '' },
{ name: 'vgdsszs', weight: 67, children: [], parent: '' },
{ name: 'lswutyd', weight: 60, children: [], parent: '' },
{ name: 'egyfwny', weight: 73, children: [], parent: '' },
{ name: 'wyiec', weight: 56, children: [], parent: '' },
{ name: 'qeayjnt', weight: 31, children: [ 'qbaig', 'yhhnavm', 'eplltu'], parent: '' },
{ name: 'tjzkwy', weight: 59, children: [], parent: '' },
{ name: 'vwtsdsf', weight: 251, children: [], parent: '' },
{ name: 'jzbnq', weight: 78, children: [], parent: '' },
{ name: 'gtbmrcp', weight: 303, children: [], parent: '' },
{ name: 'pzoaqn', weight: 94, children: [ 'ierop', 'llepsqz'], parent: '' },
{ name: 'oqfiqf', weight: 185, children: [ 'nirov', 'pyzbqz'], parent: '' },
{ name: 'kjtwz', weight: 97, children: [], parent: '' },
{ name: 'gmrkqq', weight: 86, children: [], parent: '' },
{ name: 'nnkru', weight: 16, children: [], parent: '' },
{ name: 'nnpvdm', weight: 5, children: [], parent: '' },
{ name: 'rlgrkq', weight: 9, children: [ 'uakxuru', 'qvzjgne', 'xhrqzk', 'xatzz', 'hwfzj'], parent: '' },
{ name: 'oukuy', weight: 85, children: [], parent: '' },
{ name: 'gsiokvq', weight: 80, children: [ 'tcbxnrf', 'mfunt', 'tyqnwi', 'yzxqqx', 'ehpdfno', 'oqfiqf', 'clizzo'], parent: '' },
{ name: 'qluzb', weight: 58, children: [], parent: '' },
{ name: 'bzorz', weight: 66, children: [ 'ulgrn', 'kjmvhpa'], parent: '' },
{ name: 'iqckb', weight: 103, children: [ 'zuaamot', 'knfath'], parent: '' },
{ name: 'zikmmr', weight: 87, children: [], parent: '' },
{ name: 'ugplhkq', weight: 58, children: [], parent: '' },
{ name: 'vddarvs', weight: 28, children: [], parent: '' },
{ name: 'agsfbkx', weight: 40, children: [], parent: '' },
{ name: 'riuwg', weight: 63, children: [], parent: '' },
{ name: 'mmprixv', weight: 66, children: [], parent: '' },
{ name: 'pimzjjp', weight: 58, children: [ 'dresofi', 'riogonj', 'encjlzj', 'rvmntl'], parent: '' },
{ name: 'eiekcd', weight: 66, children: [], parent: '' },
{ name: 'gxuovng', weight: 38, children: [], parent: '' },
{ name: 'vfdulx', weight: 6, children: [ 'bhnwdot', 'qxqdyx'], parent: '' },
{ name: 'iizpgi', weight: 84, children: [], parent: '' },
{ name: 'ctvrea', weight: 54, children: [], parent: '' },
{ name: 'qscadxk', weight: 28, children: [ 'hrrqb', 'yxfmelm', 'roojn'], parent: '' },
{ name: 'qxqdyx', weight: 50, children: [], parent: '' },
{ name: 'vmkib', weight: 527, children: [ 'ltccbob', 'lvktp', 'nuoic'], parent: '' },
{ name: 'mwpejh', weight: 82, children: [], parent: '' },
{ name: 'gwgchq', weight: 74, children: [], parent: '' },
{ name: 'hjxzwnq', weight: 97, children: [], parent: '' },
{ name: 'wisdd', weight: 75, children: [ 'vsmdkp', 'vzxet', 'jvqfj'], parent: '' },
{ name: 'bsvoy', weight: 260, children: [], parent: '' },
{ name: 'pmunsu', weight: 17, children: [], parent: '' },
{ name: 'kbvzpv', weight: 24, children: [ 'vybmch', 'nkwisjd', 'ihkcorh', 'bmyme', 'pjamo'], parent: '' },
{ name: 'xlkvx', weight: 55, children: [], parent: '' },
{ name: 'uezxhid', weight: 58, children: [ 'brapqvt', 'cbmkl', 'ijpzp', 'werskvv'], parent: '' },
{ name: 'qoppte', weight: 52, children: [], parent: '' },
{ name: 'oxlvr', weight: 60, children: [], parent: '' },
{ name: 'fuwekd', weight: 55, children: [], parent: '' },
{ name: 'qgytb', weight: 10, children: [], parent: '' },
{ name: 'vhbtdr', weight: 5, children: [], parent: '' },
{ name: 'rtromur', weight: 217, children: [ 'qbtixl', 'nrphw'], parent: '' },
{ name: 'mmriyf', weight: 149, children: [ 'zpkhzqb', 'kmegj'], parent: '' },
{ name: 'nukpse', weight: 7, children: [], parent: '' },
{ name: 'hdvcgn', weight: 56, children: [ 'tjzkwy', 'arouwsi'], parent: '' },
{ name: 'ghatw', weight: 920, children: [ 'jezubi', 'kpwvh', 'ywonug'], parent: '' },
{ name: 'vcoszdq', weight: 31, children: [], parent: '' },
{ name: 'vcauqo', weight: 166, children: [ 'hfjpir', 'toaan'], parent: '' },
{ name: 'fenymdp', weight: 55, children: [], parent: '' },
{ name: 'rrnkqx', weight: 41, children: [], parent: '' },
{ name: 'bsythck', weight: 59, children: [], parent: '' },
{ name: 'uyedi', weight: 1348, children: [ 'uxhpm', 'rtseps', 'kfkhxg', 'byjcsn'], parent: '' },
{ name: 'xwydsz', weight: 85, children: [], parent: '' },
{ name: 'fecwfs', weight: 20, children: [], parent: '' },
{ name: 'vxfyyd', weight: 60, children: [], parent: '' },
{ name: 'atxfply', weight: 233, children: [ 'mckyvtt', 'blfinsi'], parent: '' },
{ name: 'skrsezs', weight: 93, children: [], parent: '' },
{ name: 'cncoep', weight: 72, children: [ 'bgudw', 'qbhvu'], parent: '' },
{ name: 'awyhreh', weight: 57, children: [ 'htuuzu', 'eudowc', 'knvxq', 'felksho', 'dcjiqny'], parent: '' },
{ name: 'kpwvh', weight: 146, children: [ 'kgbjthh', 'iljkad'], parent: '' },
{ name: 'gmxdpc', weight: 42, children: [], parent: '' },
{ name: 'xxleimo', weight: 37, children: [], parent: '' },
{ name: 'hjbac', weight: 80, children: [], parent: '' },
{ name: 'twblj', weight: 191, children: [ 'tbutks', 'indjoox'], parent: '' },
{ name: 'qbtixl', weight: 7, children: [], parent: '' },
{ name: 'hubzsdn', weight: 102, children: [ 'zeiqoz', 'ukbzl'], parent: '' },
{ name: 'yhadh', weight: 85, children: [ 'twqkuk', 'fhimhm'], parent: '' },
{ name: 'injlqnw', weight: 37, children: [ 'hmrzqlh', 'lmrzi'], parent: '' },
{ name: 'vwmyqub', weight: 96, children: [], parent: '' },
{ name: 'omeew', weight: 73, children: [ 'kbdnbnd', 'rvtus'], parent: '' },
{ name: 'efsanp', weight: 33, children: [ 'loaft', 'wkbqm', 'suiagk'], parent: '' },
{ name: 'frkjf', weight: 114, children: [ 'ziyive', 'mdcxis'], parent: '' },
{ name: 'uybuil', weight: 44, children: [ 'vabii', 'iawzjqd'], parent: '' },
{ name: 'mjrfrb', weight: 35, children: [ 'nbhdty', 'lluabej'], parent: '' },
{ name: 'xhrqzk', weight: 311, children: [ 'aktnest', 'ixoas'], parent: '' },
{ name: 'yzxqqx', weight: 66, children: [ 'acbakwi', 'kqqegw', 'hmxxv'], parent: '' },
{ name: 'ikyzq', weight: 4037, children: [ 'oykurjk', 'qfsmgqe', 'biemun', 'zatfti'], parent: '' },
{ name: 'akght', weight: 55, children: [], parent: '' },
{ name: 'mbzzt', weight: 877, children: [ 'kxbmr', 'iivwxhd', 'ddumyx', 'kcxllz'], parent: '' },
{ name: 'ztpawhz', weight: 52, children: [], parent: '' },
{ name: 'zzkusct', weight: 77, children: [ 'qrwzvrb', 'wnjjug'], parent: '' },
{ name: 'gujegtc', weight: 27, children: [ 'bddlvs', 'lcjjc'], parent: '' },
{ name: 'rulju', weight: 14, children: [ 'dgwrgu', 'iruee', 'awxygg'], parent: '' },
{ name: 'djodqp', weight: 82, children: [ 'tqepyv', 'huxtvqc', 'loykzr'], parent: '' },
{ name: 'vrhltmp', weight: 77, children: [], parent: '' },
{ name: 'zozcoqd', weight: 487, children: [ 'alvjc', 'ahism', 'zzkusct', 'tlics', 'rbiarxk'], parent: '' },
{ name: 'ymxqafr', weight: 93, children: [], parent: '' },
{ name: 'vmttcwe', weight: 2318, children: [ 'zumdwwu', 'lvazjz', 'qhiav'], parent: '' },
{ name: 'prcclw', weight: 18, children: [], parent: '' },
{ name: 'gicwr', weight: 21, children: [], parent: '' },
{ name: 'ukwlfcf', weight: 1818, children: [ 'twblj', 'vpbec', 'wifaf'], parent: '' },
{ name: 'fvhvq', weight: 32, children: [], parent: '' },
{ name: 'jvtky', weight: 25, children: [], parent: '' },
{ name: 'tcjsqp', weight: 96, children: [], parent: '' },
{ name: 'rdgowwr', weight: 18, children: [], parent: '' },
{ name: 'yfwwrkp', weight: 156, children: [], parent: '' },
{ name: 'sejncwk', weight: 626, children: [ 'sjbqzk', 'acfnchg', 'pzoaqn'], parent: '' },
{ name: 'edwlns', weight: 34, children: [], parent: '' },
{ name: 'qiund', weight: 36, children: [], parent: '' },
{ name: 'cmenpt', weight: 53, children: [ 'ygmnsct', 'xwydsz'], parent: '' },
{ name: 'syojg', weight: 99, children: [ 'mwpejh', 'myoyl'], parent: '' },
{ name: 'aqbnaso', weight: 91, children: [], parent: '' },
{ name: 'ovrgyv', weight: 90, children: [], parent: '' },
{ name: 'ilpjk', weight: 8, children: [], parent: '' },
{ name: 'fvydfl', weight: 68, children: [], parent: '' },
{ name: 'fxzqvoh', weight: 231, children: [ 'rmmxnk', 'vhbtdr', 'xmjpazn', 'sbbbog'], parent: '' },
{ name: 'quohxia', weight: 68, children: [], parent: '' },
{ name: 'funabvw', weight: 153, children: [ 'vkhdfmv', 'igceh'], parent: '' },
{ name: 'mvxud', weight: 79, children: [], parent: '' },
{ name: 'rttwi', weight: 35, children: [ 'tcjsqp', 'amslmyk', 'vwmyqub'], parent: '' },
{ name: 'yjyyq', weight: 75, children: [ 'uknqlj', 'trqlfrt'], parent: '' },
{ name: 'ulgrn', weight: 20, children: [], parent: '' },
{ name: 'sfpnzbo', weight: 16, children: [], parent: '' },
{ name: 'iiwpsx', weight: 1466, children: [ 'coxpxpj', 'tlxdji', 'euoskfi'], parent: '' },
{ name: 'rhtqj', weight: 249, children: [], parent: '' },
{ name: 'sdjxpp', weight: 41, children: [], parent: '' },
{ name: 'qmyohe', weight: 21, children: [], parent: '' },
{ name: 'bljppq', weight: 30, children: [], parent: '' },
{ name: 'zskam', weight: 845, children: [ 'tpabsyz', 'wynyd', 'gtmud', 'aqbnaso'], parent: '' },
{ name: 'iqhpby', weight: 1769, children: [ 'zlvjnx', 'iufvcm', 'nfwcuci'], parent: '' },
{ name: 'brabcb', weight: 99, children: [], parent: '' },
{ name: 'byvwheg', weight: 82, children: [], parent: '' },
{ name: 'epstabj', weight: 38, children: [], parent: '' },
{ name: 'phdeae', weight: 92, children: [ 'zwcsjgs', 'kdqctmq'], parent: '' },
{ name: 'xyjsuy', weight: 8, children: [], parent: '' },
{ name: 'owtswi', weight: 167, children: [], parent: '' },
{ name: 'htlfqi', weight: 60, children: [], parent: '' },
{ name: 'ybgdelp', weight: 24, children: [], parent: '' },
{ name: 'ehwcxy', weight: 63, children: [], parent: '' },
{ name: 'corcne', weight: 217, children: [], parent: '' },
{ name: 'tlzlq', weight: 28, children: [], parent: '' },
{ name: 'hlfmvdt', weight: 12, children: [ 'meqla', 'yywjam'], parent: '' },
{ name: 'jwmjz', weight: 5, children: [], parent: '' },
{ name: 'syhipz', weight: 76, children: [ 'qwror', 'rzsggfj', 'mjuyo', 'zitvhwp'], parent: '' },
{ name: 'nfwcuci', weight: 214, children: [], parent: '' },
{ name: 'pvniw', weight: 42, children: [], parent: '' },
{ name: 'wknmdh', weight: 836, children: [ 'thbazqq', 'rpbeiqg', 'lyvdkxe'], parent: '' },
{ name: 'guvto', weight: 32, children: [], parent: '' },
{ name: 'isispf', weight: 151, children: [ 'kvsprca', 'yoiej'], parent: '' },
{ name: 'hasclc', weight: 46, children: [], parent: '' },
{ name: 'kxbmr', weight: 116, children: [ 'jsdbgko', 'mvyzuw'], parent: '' },
{ name: 'akgfzo', weight: 46, children: [ 'glblkz', 'lpfahc'], parent: '' },
{ name: 'jfssr', weight: 14, children: [], parent: '' },
{ name: 'bxjqibv', weight: 44, children: [], parent: '' },
{ name: 'jxraf', weight: 15, children: [], parent: '' },
{ name: 'hfwpcsa', weight: 197, children: [], parent: '' },
{ name: 'htuuzu', weight: 30, children: [ 'cmfcqh', 'xvoehjz', 'jabfysb', 'rfllomn', 'mvybmye', 'rttwi'], parent: '' },
{ name: 'wfcqzm', weight: 95, children: [], parent: '' },
{ name: 'quolxjw', weight: 84, children: [], parent: '' },
{ name: 'rergyy', weight: 56, children: [], parent: '' },
{ name: 'awnafxx', weight: 29, children: [], parent: '' },
{ name: 'bzuago', weight: 99, children: [], parent: '' },
{ name: 'ytzdrvj', weight: 28, children: [], parent: '' },
{ name: 'yoiej', weight: 65, children: [], parent: '' },
{ name: 'ffijsc', weight: 81, children: [], parent: '' },
{ name: 'rjqjwjy', weight: 73, children: [], parent: '' },
{ name: 'wnjjug', weight: 68, children: [], parent: '' },
{ name: 'ybnsg', weight: 78, children: [], parent: '' },
{ name: 'ygmnsct', weight: 85, children: [], parent: '' },
{ name: 'qiaej', weight: 82, children: [], parent: '' },
{ name: 'gzriygp', weight: 58, children: [], parent: '' },
{ name: 'zeiqoz', weight: 14, children: [], parent: '' },
{ name: 'jqgkz', weight: 59, children: [], parent: '' },
{ name: 'iawzjqd', weight: 89, children: [], parent: '' },
{ name: 'sxwbzyj', weight: 45, children: [], parent: '' },
{ name: 'faqxj', weight: 33, children: [], parent: '' },
{ name: 'gixsbr', weight: 1173, children: [ 'qvrtwdt', 'wkxlf', 'iiwpsx', 'icspwbg', 'qhfmjrm', 'mspxpr', 'xsuxhbq'], parent: '' },
{ name: 'ktffksv', weight: 29, children: [], parent: '' },
{ name: 'mfunt', weight: 165, children: [ 'quolxjw', 'tgwiasr'], parent: '' },
{ name: 'lzevbng', weight: 16, children: [], parent: '' },
{ name: 'azttml', weight: 15, children: [], parent: '' },
{ name: 'hezkdc', weight: 193, children: [ 'mpieb', 'voawog'], parent: '' },
{ name: 'dsoyvp', weight: 55, children: [ 'pfxoef', 'eiekcd'], parent: '' },
{ name: 'ildgly', weight: 137, children: [ 'pvniw', 'ulszlax', 'gtxdtf'], parent: '' },
{ name: 'paaqws', weight: 214, children: [], parent: '' },
{ name: 'chcnreg', weight: 33, children: [], parent: '' },
{ name: 'rpyxxhm', weight: 53, children: [], parent: '' },
{ name: 'kemxmk', weight: 332, children: [ 'umtmwow', 'yahsymr'], parent: '' },
{ name: 'enmxpmj', weight: 64, children: [], parent: '' },
{ name: 'owjtoo', weight: 63, children: [], parent: '' },
{ name: 'iaoxdmm', weight: 138, children: [ 'xyjsuy', 'fzltz'], parent: '' },
{ name: 'oykurjk', weight: 868, children: [ 'hkjcnv', 'qscadxk', 'phhumfd'], parent: '' },
{ name: 'eawwls', weight: 73, children: [], parent: '' },
{ name: 'kiryhz', weight: 44, children: [], parent: '' },
{ name: 'janbnmh', weight: 15, children: [], parent: '' },
{ name: 'sbbbog', weight: 5, children: [], parent: '' },
{ name: 'sfjyf', weight: 210, children: [ 'xpdmegi', 'niavkxg', 'eevdo', 'vgkjgy'], parent: '' },
{ name: 'lwnlk', weight: 47, children: [], parent: '' },
{ name: 'cthyz', weight: 62, children: [], parent: '' },
{ name: 'wsrrryh', weight: 64, children: [], parent: '' },
{ name: 'yahzcyp', weight: 64, children: [ 'sddoa', 'yscpg'], parent: '' },
{ name: 'kigsmv', weight: 22, children: [], parent: '' },
{ name: 'rubvop', weight: 31, children: [], parent: '' },
{ name: 'ajgvmuy', weight: 80, children: [], parent: '' },
{ name: 'htwzu', weight: 16, children: [], parent: '' },
{ name: 'xatzz', weight: 157, children: [ 'ucahbv', 'qiaej'], parent: '' },
{ name: 'uzprj', weight: 58, children: [], parent: '' },
{ name: 'ltceq', weight: 99, children: [], parent: '' },
{ name: 'dnqdmxc', weight: 79, children: [], parent: '' },
{ name: 'pmpxq', weight: 13, children: [], parent: '' },
{ name: 'ebyfpmf', weight: 79, children: [], parent: '' },
{ name: 'qeuwgn', weight: 36, children: [], parent: '' },
{ name: 'osbndxb', weight: 23, children: [], parent: '' },
{ name: 'qunom', weight: 178, children: [ 'jxhhgvz', 'jjfoqtv'], parent: '' },
{ name: 'xinxep', weight: 1670, children: [ 'tewltq', 'qtmvya', 'gixsbr'], parent: '' },
{ name: 'clrhsr', weight: 19, children: [], parent: '' },
{ name: 'ierop', weight: 96, children: [], parent: '' },
{ name: 'wkxlf', weight: 1022, children: [ 'drwwnwd', 'finxtiu', 'dkwwoa'], parent: '' },
{ name: 'ogziig', weight: 64, children: [], parent: '' },
{ name: 'nsqiicp', weight: 27, children: [], parent: '' },
{ name: 'fkehyrg', weight: 75, children: [], parent: '' },
{ name: 'zielffk', weight: 23, children: [], parent: '' },
{ name: 'upatvy', weight: 95, children: [], parent: '' },
{ name: 'jxhhgvz', weight: 16, children: [], parent: '' },
{ name: 'swqres', weight: 26, children: [], parent: '' },
{ name: 'ndmpgss', weight: 89, children: [], parent: '' },
{ name: 'wzvsi', weight: 69, children: [], parent: '' },
{ name: 'ihkcorh', weight: 183, children: [ 'fsjvyxv', 'hmemann'], parent: '' },
{ name: 'elgvwug', weight: 67, children: [], parent: '' },
{ name: 'ujzxlx', weight: 98, children: [], parent: '' },
{ name: 'veiljb', weight: 45, children: [], parent: '' },
{ name: 'hrrqb', weight: 57, children: [], parent: '' },
{ name: 'lrlhwat', weight: 22, children: [], parent: '' },
{ name: 'xlkdss', weight: 7, children: [], parent: '' },
{ name: 'qibrsjj', weight: 60, children: [], parent: '' },
{ name: 'ytjheqk', weight: 30, children: [], parent: '' },
{ name: 'ojnxwzq', weight: 2529, children: [ 'tvoptyn', 'yysyjbk', 'kqfgnql', 'uwrcgnq'], parent: '' },
{ name: 'kbfpx', weight: 47, children: [], parent: '' },
{ name: 'afbnq', weight: 41, children: [], parent: '' },
{ name: 'yscpg', weight: 46, children: [], parent: '' },
{ name: 'yatdg', weight: 50, children: [], parent: '' },
{ name: 'acbakwi', weight: 89, children: [], parent: '' },
{ name: 'bcedyx', weight: 37, children: [], parent: '' },
{ name: 'aktnest', weight: 5, children: [], parent: '' },
{ name: 'fkmpv', weight: 31, children: [], parent: '' },
{ name: 'kgbjthh', weight: 14, children: [], parent: '' },
{ name: 'gtmud', weight: 91, children: [], parent: '' },
{ name: 'alvjc', weight: 139, children: [ 'qdemebr', 'xxleimo'], parent: '' },
{ name: 'yedvssr', weight: 205, children: [ 'fvkew', 'gicwr'], parent: '' },
{ name: 'ejlya', weight: 66, children: [], parent: '' },
{ name: 'mhkrny', weight: 672, children: [ 'bezoxx', 'haano', 'pggrr'], parent: '' },
{ name: 'edfxg', weight: 74, children: [], parent: '' },
{ name: 'bmyme', weight: 95, children: [ 'wsdqchf', 'yhtpdwu'], parent: '' },
{ name: 'uedozkm', weight: 5333, children: [ 'tntns', 'mkslglr', 'zgkxkj', 'sejncwk'], parent: '' },
{ name: 'hsywhj', weight: 154, children: [], parent: '' },
{ name: 'licst', weight: 9, children: [], parent: '' },
{ name: 'gtbocpw', weight: 60, children: [], parent: '' },
{ name: 'vdwutc', weight: 90, children: [], parent: '' },
{ name: 'ulkdq', weight: 82, children: [], parent: '' },
{ name: 'ceutto', weight: 21, children: [], parent: '' },
{ name: 'sivsece', weight: 73, children: [], parent: '' },
{ name: 'tntns', weight: 1094, children: [ 'djodqp', 'ixuvbk', 'hubzsdn'], parent: '' },
{ name: 'qhfmjrm', weight: 1628, children: [ 'xmhdsio', 'myzut', 'dfupxk'], parent: '' },
{ name: 'rzsggfj', weight: 317, children: [ 'udlhalx', 'narnhty'], parent: '' },
{ name: 'hlshpkq', weight: 99, children: [ 'zpuwyqp', 'zqaxyz'], parent: '' },
{ name: 'ijpzp', weight: 78, children: [], parent: '' },
{ name: 'qtmvya', weight: 14, children: [ 'gsiokvq', 'wanxt', 'kskkjn', 'adtpk', 'iqhpby', 'pcehxbx'], parent: '' },
{ name: 'ktoxuar', weight: 83, children: [ 'eawwls', 'tvfptpz'], parent: '' },
{ name: 'uwehdau', weight: 55, children: [], parent: '' },
{ name: 'advjges', weight: 20, children: [], parent: '' },
{ name: 'iuubp', weight: 62, children: [], parent: '' },
{ name: 'encjlzj', weight: 49, children: [ 'ltceq', 'brabcb', 'uyoez'], parent: '' },
{ name: 'pabkgnq', weight: 10, children: [], parent: '' },
{ name: 'ulxscm', weight: 35, children: [], parent: '' },
{ name: 'rcbhgw', weight: 832, children: [ 'jrott', 'hcvwov', 'akgfzo'], parent: '' },
{ name: 'nevhjg', weight: 17, children: [], parent: '' },
{ name: 'agtab', weight: 41, children: [ 'ztpawhz', 'dsiixv', 'gipbso', 'nholw'], parent: '' },
{ name: 'xjbtfms', weight: 33, children: [], parent: '' },
{ name: 'mfcutqz', weight: 219, children: [ 'ncbrxsy', 'bnwotj'], parent: '' },
{ name: 'txhxoib', weight: 240, children: [ 'qgytb', 'pabkgnq'], parent: '' },
{ name: 'miwjfr', weight: 20, children: [], parent: '' },
{ name: 'vkmxs', weight: 75, children: [], parent: '' },
{ name: 'hidzw', weight: 55, children: [], parent: '' },
{ name: 'whjbc', weight: 54, children: [], parent: '' },
{ name: 'ivhtlxa', weight: 17, children: [], parent: '' },
{ name: 'jgylf', weight: 98, children: [], parent: '' },
{ name: 'iydqii', weight: 55, children: [], parent: '' },
{ name: 'gkitfsr', weight: 23, children: [], parent: '' },
{ name: 'carfsnj', weight: 79, children: [], parent: '' },
{ name: 'pxkzk', weight: 5, children: [], parent: '' },
{ name: 'wlwnand', weight: 87, children: [], parent: '' },
{ name: 'khdzsr', weight: 73, children: [], parent: '' },
{ name: 'tqepyv', weight: 16, children: [], parent: '' },
{ name: 'gsdzpjh', weight: 40, children: [], parent: '' },
{ name: 'wnmnz', weight: 290, children: [ 'rywggm', 'hpfmhy', 'frkjf', 'ojpghb', 'wgjst', 'ivldghm'], parent: '' },
{ name: 'msyvs', weight: 32, children: [ 'kyhezqn', 'dkegbrt', 'enogehk'], parent: '' },
{ name: 'uusec', weight: 41, children: [], parent: '' },
{ name: 'ufdbsy', weight: 132, children: [ 'mrmuat', 'seuaftr'], parent: '' },
{ name: 'vwupkmh', weight: 53, children: [], parent: '' },
{ name: 'pthnz', weight: 34, children: [ 'fjkfpm', 'uedozkm', 'hoqti', 'efgdfa'], parent: '' },
{ name: 'jzwusi', weight: 188, children: [ 'edagh', 'xrknksz', 'syxdt', 'xeege'], parent: '' },
{ name: 'npblyaq', weight: 35, children: [ 'mnfknb', 'jdjkbwr', 'aixwgk', 'ducdc'], parent: '' },
{ name: 'mdvnu', weight: 42, children: [], parent: '' },
{ name: 'qcglune', weight: 68, children: [], parent: '' },
{ name: 'jafsqqu', weight: 41, children: [], parent: '' },
{ name: 'nderndc', weight: 63, children: [], parent: '' },
{ name: 'qtshuo', weight: 44, children: [], parent: '' },
{ name: 'twqkuk', weight: 66, children: [], parent: '' },
{ name: 'fcdutzs', weight: 8, children: [], parent: '' },
{ name: 'olgmto', weight: 702, children: [ 'lbwgsap', 'jakmbx', 'aufwfrp', 'osnpbou'], parent: '' },
{ name: 'pfekvok', weight: 34, children: [], parent: '' },
{ name: 'cbmkr', weight: 93, children: [ 'pjzcs', 'pavtnxe', 'nsoju'], parent: '' },
{ name: 'igceh', weight: 36, children: [], parent: '' },
{ name: 'blvyrzh', weight: 10, children: [ 'vdwutc', 'cneww', 'mkykc', 'ovrgyv'], parent: '' },
{ name: 'mtxzek', weight: 136, children: [ 'kfefhun', 'wnpkwy'], parent: '' },
{ name: 'bsxtebe', weight: 71, children: [ 'idnsypp', 'iqfnj'], parent: '' },
{ name: 'bntzksk', weight: 37289, children: [ 'vmttcwe', 'ukwlfcf', 'zzpevgd'], parent: '' },
{ name: 'eudowc', weight: 1052, children: [ 'mjrfrb', 'uxsisng', 'yawmlbb', 'ktoxuar'], parent: '' },
{ name: 'mcghosj', weight: 41, children: [], parent: '' },
{ name: 'ojpghb', weight: 156, children: [ 'prcclw', 'gytzi'], parent: '' },
{ name: 'osrdt', weight: 79, children: [], parent: '' },
{ name: 'vqrrii', weight: 60, children: [ 'zrgqfb', 'ffijsc'], parent: '' },
{ name: 'wkgouh', weight: 53, children: [], parent: '' },
{ name: 'nsvwcl', weight: 90, children: [], parent: '' },
{ name: 'eumefa', weight: 84, children: [], parent: '' },
{ name: 'zuaamot', weight: 32, children: [], parent: '' },
{ name: 'lxdji', weight: 8, children: [], parent: '' },
{ name: 'zeebqts', weight: 24, children: [], parent: '' },
{ name: 'yktye', weight: 24, children: [], parent: '' },
{ name: 'wswnja', weight: 117, children: [ 'fnkrew', 'mcmzs'], parent: '' },
{ name: 'vtqzf', weight: 17, children: [], parent: '' },
{ name: 'kmnzz', weight: 5, children: [ 'wtsqx', 'ocqrpkf', 'hasclc', 'kqdseyh'], parent: '' },
{ name: 'ednlrw', weight: 56, children: [], parent: '' },
{ name: 'yxfmelm', weight: 57, children: [], parent: '' },
{ name: 'fgeup', weight: 36, children: [], parent: '' },
{ name: 'oiufrau', weight: 43, children: [ 'ajgvmuy', 'kxzwel', 'hjbac'], parent: '' },
{ name: 'bdvtnul', weight: 26, children: [], parent: '' },
{ name: 'xayqwyj', weight: 168, children: [ 'wvdswpz', 'fvaeyq'], parent: '' },
{ name: 'vzxet', weight: 60, children: [], parent: '' },
{ name: 'cvvkno', weight: 56, children: [], parent: '' },
{ name: 'wctihs', weight: 31, children: [ 'ikicwez', 'wzvsi'], parent: '' },
{ name: 'cpzwgk', weight: 209, children: [ 'lwnlk', 'xvudg'], parent: '' },
{ name: 'fsoqc', weight: 24, children: [], parent: '' },
{ name: 'hkkzpzh', weight: 14, children: [], parent: '' },
{ name: 'wfeurd', weight: 165, children: [ 'nlrbcxx', 'kbbwe'], parent: '' },
{ name: 'klexq', weight: 30, children: [], parent: '' },
{ name: 'ebjgfh', weight: 34, children: [], parent: '' },
{ name: 'vctupmx', weight: 42, children: [], parent: '' },
{ name: 'psrup', weight: 53, children: [], parent: '' },
{ name: 'ngiol', weight: 95, children: [], parent: '' },
{ name: 'kryvxoc', weight: 18, children: [], parent: '' },
{ name: 'tzkgrjf', weight: 54, children: [], parent: '' },
{ name: 'gcrugvi', weight: 62, children: [], parent: '' },
{ name: 'jxhhc', weight: 17, children: [], parent: '' },
{ name: 'wntfmtn', weight: 254, children: [ 'faqxj', 'qzgdlb', 'uurqa'], parent: '' },
{ name: 'wuyjdn', weight: 95, children: [], parent: '' },
{ name: 'dbrcg', weight: 11, children: [], parent: '' },
{ name: 'dcwcs', weight: 42, children: [], parent: '' },
{ name: 'dsuchz', weight: 88, children: [], parent: '' },
{ name: 'hlykzp', weight: 31, children: [], parent: '' },
{ name: 'pwyfdan', weight: 85, children: [], parent: '' },
{ name: 'hmemann', weight: 27, children: [], parent: '' },
{ name: 'yjmjnm', weight: 77, children: [], parent: '' },
{ name: 'cjcytbb', weight: 55, children: [], parent: '' },
{ name: 'sutzt', weight: 169, children: [ 'fpdoney', 'nnkru', 'sfpnzbo'], parent: '' },
{ name: 'lvazjz', weight: 39, children: [ 'zinjsj', 'abjmd'], parent: '' },
{ name: 'bfozr', weight: 43, children: [], parent: '' },
{ name: 'gfvzrt', weight: 84, children: [], parent: '' },
{ name: 'wanxt', weight: 1603, children: [ 'lgqwxgu', 'shwsf', 'zvnzep', 'jwrmi'], parent: '' },
{ name: 'fntaap', weight: 43, children: [], parent: '' },
{ name: 'dfupxk', weight: 91, children: [], parent: '' },
{ name: 'uxsisng', weight: 95, children: [ 'elgvwug', 'ssxqkhq'], parent: '' },
{ name: 'rflrj', weight: 181, children: [ 'niklue', 'yjcggu'], parent: '' },
{ name: 'narnhty', weight: 26, children: [], parent: '' },
{ name: 'ziyive', weight: 39, children: [], parent: '' },
{ name: 'tkvip', weight: 279, children: [], parent: '' },
{ name: 'xjjvneg', weight: 19, children: [], parent: '' },
{ name: 'toaan', weight: 19, children: [], parent: '' },
{ name: 'tgoztyw', weight: 201, children: [ 'yrnjhqc', 'rzldn'], parent: '' },
{ name: 'nrphw', weight: 7, children: [], parent: '' },
{ name: 'bhnwdot', weight: 50, children: [], parent: '' },
{ name: 'negxuk', weight: 217, children: [ 'nsqiicp', 'xsvage'], parent: '' },
{ name: 'tyqnwi', weight: 155, children: [ 'kigpl', 'iwkotv'], parent: '' },
{ name: 'qbhyq', weight: 98, children: [], parent: '' },
{ name: 'qmeawpu', weight: 22, children: [], parent: '' },
{ name: 'xjejd', weight: 88, children: [], parent: '' },
{ name: 'pvbgvb', weight: 41, children: [], parent: '' },
{ name: 'snsyzbk', weight: 20, children: [], parent: '' },
{ name: 'vkile', weight: 164, children: [ 'pdkfixk', 'ufpdyq', 'lrlhwat', 'kigsmv'], parent: '' },
{ name: 'jdazgj', weight: 17, children: [], parent: '' },
{ name: 'cdaazt', weight: 54, children: [], parent: '' },
{ name: 'qtcnfy', weight: 50, children: [], parent: '' },
{ name: 'gwyrtw', weight: 52, children: [], parent: '' },
{ name: 'sgznbm', weight: 50, children: [], parent: '' },
{ name: 'gkqxb', weight: 65, children: [ 'ioyealn', 'rqeftjw'], parent: '' },
{ name: 'mgoym', weight: 83, children: [ 'kslvs', 'snyio'], parent: '' },
{ name: 'cneww', weight: 90, children: [], parent: '' },
{ name: 'fixqj', weight: 116, children: [ 'ybzqe', 'nhcmgrr', 'nevhjg'], parent: '' },
{ name: 'kjmvhpa', weight: 20, children: [], parent: '' },
{ name: 'sntbr', weight: 55, children: [], parent: '' },
{ name: 'bnwotj', weight: 15, children: [], parent: '' },
{ name: 'xvudg', weight: 47, children: [], parent: '' },
{ name: 'ltyxiwk', weight: 53, children: [], parent: '' },
{ name: 'brapqvt', weight: 78, children: [], parent: '' },
{ name: 'zrmzpo', weight: 95, children: [], parent: '' },
{ name: 'xcdswr', weight: 85, children: [], parent: '' },
{ name: 'erngeah', weight: 44, children: [], parent: '' },
{ name: 'zvogn', weight: 8, children: [], parent: '' },
{ name: 'ranlxct', weight: 59, children: [], parent: '' },
{ name: 'oztxjfl', weight: 239, children: [ 'eukyl', 'pjpbcq'], parent: '' },
{ name: 'bcrso', weight: 24, children: [], parent: '' },
{ name: 'ogtxa', weight: 89, children: [ 'iuubp', 'gcrugvi', 'cthyz', 'zzlocxd'], parent: '' },
{ name: 'utpyp', weight: 35, children: [], parent: '' },
{ name: 'rmmxnk', weight: 5, children: [], parent: '' },
{ name: 'nogoyp', weight: 70, children: [ 'rdgowwr', 'kryvxoc'], parent: '' },
{ name: 'afqwh', weight: 30, children: [], parent: '' },
{ name: 'nedjj', weight: 54, children: [], parent: '' },
{ name: 'lyvdkxe', weight: 42, children: [ 'ssblis', 'gmrkqq'], parent: '' },
{ name: 'ybzqe', weight: 17, children: [], parent: '' },
{ name: 'bnvjfq', weight: 34, children: [], parent: '' },
{ name: 'sklld', weight: 24, children: [], parent: '' },
{ name: 'eqkio', weight: 2131, children: [ 'eefmcrp', 'cmenpt', 'wswnja'], parent: '' },
{ name: 'qypsl', weight: 54, children: [], parent: '' },
{ name: 'wcfykko', weight: 60, children: [], parent: '' },
{ name: 'luiiv', weight: 898, children: [ 'vgnkq', 'coenr', 'paaqws'], parent: '' },
{ name: 'mjpmw', weight: 101, children: [ 'lomxh', 'rqvifq'], parent: '' },
{ name: 'wswwck', weight: 40, children: [ 'zmdvl', 'yatdg', 'sgznbm'], parent: '' },
{ name: 'yjcggu', weight: 18, children: [], parent: '' },
{ name: 'pjpbcq', weight: 22, children: [], parent: '' },
{ name: 'yahsymr', weight: 30, children: [], parent: '' },
{ name: 'liwvq', weight: 1960, children: [ 'axqifwm', 'qunom', 'euxvn', 'efsanp'], parent: '' },
{ name: 'euoskfi', weight: 135, children: [ 'nnpvdm', 'jwmjz'], parent: '' },
{ name: 'hpfmhy', weight: 176, children: [ 'fuexyx', 'fcdutzs'], parent: '' },
{ name: 'jczkx', weight: 55, children: [], parent: '' },
{ name: 'jvwfxp', weight: 330, children: [ 'cvcyykp', 'hlykzp'], parent: '' },
{ name: 'pyscsi', weight: 64, children: [], parent: '' },
{ name: 'jevfpj', weight: 65, children: [], parent: '' },
{ name: 'zitvhwp', weight: 75, children: [ 'tpbcg', 'ujzxlx', 'qbhyq'], parent: '' },
{ name: 'sndject', weight: 5, children: [], parent: '' },
{ name: 'aufwfrp', weight: 53, children: [ 'mmprixv', 'ejlya'], parent: '' },
{ name: 'riogonj', weight: 346, children: [], parent: '' },
{ name: 'dhecgkl', weight: 73, children: [], parent: '' },
{ name: 'eevdo', weight: 16, children: [], parent: '' },
{ name: 'kslvs', weight: 42, children: [], parent: '' },
{ name: 'zpuktmx', weight: 37, children: [], parent: '' },
{ name: 'nbkzscx', weight: 9, children: [], parent: '' },
{ name: 'pbvcu', weight: 73, children: [], parent: '' },
{ name: 'zwymlsj', weight: 118, children: [ 'tcpvyfj', 'rtiaapt', 'xikbq', 'gldvef'], parent: '' },
{ name: 'fzbwmsz', weight: 187, children: [ 'dbrcg', 'wkkkv', 'mznsk', 'etkzf'], parent: '' },
{ name: 'tmtfhr', weight: 30, children: [], parent: '' },
{ name: 'eukyl', weight: 22, children: [], parent: '' },
{ name: 'hmugaom', weight: 156, children: [], parent: '' },
{ name: 'ixuvbk', weight: 130, children: [], parent: '' },
{ name: 'santsu', weight: 76, children: [], parent: '' },
{ name: 'buplpb', weight: 26, children: [ 'negxuk', 'imuhew', 'izssdb'], parent: '' },
{ name: 'imuhew', weight: 77, children: [ 'yauryvu', 'kjtwz'], parent: '' },
{ name: 'niklue', weight: 18, children: [], parent: '' },
{ name: 'zuzhmf', weight: 137, children: [ 'pbvcu', 'sivsece'], parent: '' },
{ name: 'lgqwxgu', weight: 202, children: [], parent: '' },
{ name: 'emxwr', weight: 262, children: [ 'nedjj', 'hwfcy'], parent: '' },
{ name: 'iqfnj', weight: 94, children: [], parent: '' },
{ name: 'ixyeq', weight: 273, children: [ 'pxkzk', 'ylfvgv'], parent: '' },
{ name: 'wvgzlw', weight: 87, children: [ 'hidzw', 'vofrtf', 'yvllxxw'], parent: '' },
{ name: 'kbbwe', weight: 41, children: [], parent: '' },
{ name: 'jcsjaxj', weight: 2792, children: [ 'buplpb', 'slntf', 'kqohkg'], parent: '' },
{ name: 'tlxdji', weight: 145, children: [], parent: '' },
{ name: 'hgaoiz', weight: 283, children: [], parent: '' },
{ name: 'tgwiasr', weight: 84, children: [], parent: '' },
{ name: 'ewyrp', weight: 259, children: [ 'jevqne', 'ilpjk', 'kmpmdb'], parent: '' },
{ name: 'kmegj', weight: 50, children: [], parent: '' },
{ name: 'axqifwm', weight: 98, children: [ 'dasmiiw', 'wyiec'], parent: '' },
{ name: 'jrrhzc', weight: 5, children: [], parent: '' },
{ name: 'cftggo', weight: 20, children: [], parent: '' },
{ name: 'xvoyybs', weight: 56, children: [ 'ygvvvq', 'kemxmk', 'jkfrln', 'arjgn', 'fvsitx', 'lfrfa', 'jvwfxp'], parent: '' },
{ name: 'daiaot', weight: 60, children: [], parent: '' },
{ name: 'avemxf', weight: 63, children: [], parent: '' },
{ name: 'yzpyzu', weight: 41, children: [], parent: '' },
{ name: 'wtbst', weight: 73, children: [], parent: '' },
{ name: 'seuaftr', weight: 21, children: [], parent: '' },
{ name: 'dgwrgu', weight: 89, children: [], parent: '' },
{ name: 'kpffozq', weight: 27, children: [], parent: '' },
{ name: 'qoeviy', weight: 129, children: [ 'yxvmxzg', 'bfxvxpl'], parent: '' },
{ name: 'uwprsvh', weight: 1502, children: [ 'qjkkohe', 'pctkyat'], parent: '' },
{ name: 'ldvcrw', weight: 299, children: [ 'clrhsr', 'elmmtp'], parent: '' },
{ name: 'yywjam', weight: 86, children: [], parent: '' },
{ name: 'elmmtp', weight: 19, children: [], parent: '' },
{ name: 'coenr', weight: 56, children: [ 'edyohkw', 'vspquqe'], parent: '' },
{ name: 'khixwdd', weight: 54, children: [ 'vxfyyd', 'dltbolj', 'htlfqi'], parent: '' },
{ name: 'jsdbgko', weight: 73, children: [], parent: '' },
{ name: 'llepsqz', weight: 96, children: [], parent: '' },
{ name: 'smqtcaj', weight: 250, children: [ 'daiaot', 'lswutyd'], parent: '' },
{ name: 'thbazqq', weight: 180, children: [ 'pmunsu', 'vtqzf'], parent: '' },
{ name: 'kaitdu', weight: 98, children: [], parent: '' },
{ name: 'fvaeyq', weight: 34, children: [], parent: '' },
{ name: 'glblkz', weight: 97, children: [], parent: '' },
{ name: 'vmofl', weight: 39, children: [ 'eumefa', 'gfvzrt'], parent: '' },
{ name: 'dqktd', weight: 95, children: [], parent: '' },
{ name: 'mwvbcqg', weight: 58, children: [], parent: '' },
{ name: 'gbwfjf', weight: 777, children: [ 'tkvip', 'mbcwjt', 'sbimooe'], parent: '' },
{ name: 'hmxxv', weight: 89, children: [], parent: '' },
{ name: 'wynyd', weight: 91, children: [], parent: '' },
{ name: 'jdjkbwr', weight: 41, children: [], parent: '' },
{ name: 'elxccty', weight: 54, children: [ 'fvydfl', 'qcglune'], parent: '' },
{ name: 'bnmuprs', weight: 41, children: [], parent: '' },
{ name: 'kgfudu', weight: 45, children: [ 'otsyp', 'sdixs', 'whjbc', 'cdaazt'], parent: '' },
{ name: 'hfjtksr', weight: 39, children: [], parent: '' },
{ name: 'tlgdija', weight: 81, children: [ 'fntaap', 'zlxlwv'], parent: '' },
{ name: 'qrwzvrb', weight: 68, children: [], parent: '' },
{ name: 'nchgm', weight: 49, children: [], parent: '' },
{ name: 'gofjvi', weight: 67, children: [], parent: '' },
{ name: 'jjfoqtv', weight: 16, children: [], parent: '' },
{ name: 'tfbqaoe', weight: 53, children: [], parent: '' },
{ name: 'zzqtmxd', weight: 116, children: [ 'fecwfs', 'eigsdc'], parent: '' },
{ name: 'qhktzou', weight: 75, children: [], parent: '' },
{ name: 'wydtqax', weight: 45, children: [], parent: '' },
{ name: 'ytyhmux', weight: 84, children: [], parent: '' },
{ name: 'qqkqhzb', weight: 274, children: [], parent: '' },
{ name: 'trqlfrt', weight: 92, children: [], parent: '' },
{ name: 'eivaf', weight: 370, children: [], parent: '' },
{ name: 'njlaepf', weight: 47, children: [], parent: '' },
{ name: 'bkmepbs', weight: 46, children: [], parent: '' },
{ name: 'mpieb', weight: 34, children: [], parent: '' },
{ name: 'sbimooe', weight: 89, children: [ 'dqktd', 'bnmsz'], parent: '' },
{ name: 'dltbolj', weight: 60, children: [], parent: '' },
{ name: 'lvktp', weight: 32, children: [ 'prnno', 'qxsjs', 'wuyjdn'], parent: '' },
{ name: 'lcius', weight: 54, children: [], parent: '' },
{ name: 'mxelfv', weight: 75, children: [], parent: '' },
{ name: 'hrwtz', weight: 17, children: [ 'mocpa', 'fixysjm', 'cjkieim'], parent: '' },
{ name: 'jzcstbe', weight: 236, children: [], parent: '' },
{ name: 'mikalda', weight: 35, children: [], parent: '' },
{ name: 'xrknksz', weight: 12, children: [], parent: '' },
{ name: 'knfath', weight: 32, children: [], parent: '' },
{ name: 'pmssap', weight: 99, children: [], parent: '' },
{ name: 'eefmcrp', weight: 209, children: [ 'nukpse', 'xlkdss'], parent: '' },
{ name: 'nkwisjd', weight: 149, children: [ 'pfltnc', 'fblsn'], parent: '' },
{ name: 'ragcph', weight: 38, children: [], parent: '' },
{ name: 'eubjf', weight: 58, children: [], parent: '' },
{ name: 'snyio', weight: 42, children: [], parent: '' },
{ name: 'zquvn', weight: 108, children: [ 'nvrpd', 'dlrznye'], parent: '' },
{ name: 'uakxuru', weight: 169, children: [ 'zhpdhat', 'uymdj'], parent: '' },
{ name: 'egrit', weight: 73, children: [], parent: '' },
{ name: 'dlvttmo', weight: 95, children: [], parent: '' },
{ name: 'xikbq', weight: 18, children: [], parent: '' },
{ name: 'xgmrufk', weight: 56, children: [], parent: '' },
{ name: 'cbmkl', weight: 78, children: [], parent: '' },
{ name: 'jqwaifx', weight: 24, children: [], parent: '' },
{ name: 'qowepn', weight: 33, children: [], parent: '' },
{ name: 'clizzo', weight: 227, children: [ 'dfrzb', 'zjxjhwc'], parent: '' },
{ name: 'tbakk', weight: 935, children: [ 'wctihs', 'vszpkfs', 'iqtdzrh'], parent: '' },
{ name: 'qvzjgne', weight: 36, children: [ 'dlvttmo', 'wfcqzm', 'mfslhp'], parent: '' },
{ name: 'mvybmye', weight: 207, children: [ 'awnafxx', 'xqrrpu', 'ktffksv', 'csbgxs'], parent: '' },
{ name: 'mkslglr', weight: 189, children: [ 'dmkhzgg', 'sykmuwo', 'bsxtebe', 'yjyyq', 'znmav'], parent: '' },
{ name: 'jkfrln', weight: 342, children: [ 'jbhohbx', 'jvtky'], parent: '' },
{ name: 'znswber', weight: 40, children: [], parent: '' },
{ name: 'rqvifq', weight: 53, children: [], parent: '' },
{ name: 'fnkrew', weight: 53, children: [], parent: '' },
{ name: 'jabfysb', weight: 91, children: [ 'gzriygp', 'eubjf', 'qluzb', 'ugplhkq'], parent: '' },
{ name: 'dresofi', weight: 346, children: [], parent: '' },
{ name: 'zpkhzqb', weight: 50, children: [], parent: '' },
{ name: 'hwraaxu', weight: 89, children: [ 'majskr', 'nchgm'], parent: '' },
{ name: 'uebmnqa', weight: 88, children: [ 'ymxqafr', 'skrsezs'], parent: '' },
{ name: 'qeoetnp', weight: 173, children: [ 'evvfcyi', 'pmpxq'], parent: '' },
{ name: 'sddoa', weight: 46, children: [], parent: '' },
{ name: 'qdemebr', weight: 37, children: [], parent: '' },
{ name: 'kobwktw', weight: 62, children: [], parent: '' },
{ name: 'fogmaih', weight: 75, children: [], parent: '' },
{ name: 'wgevvca', weight: 79, children: [], parent: '' },
{ name: 'phhumfd', weight: 35, children: [ 'ulkdq', 'ulvbf'], parent: '' },
{ name: 'zpuwyqp', weight: 59, children: [], parent: '' },
{ name: 'txdprek', weight: 83, children: [ 'gsbmh', 'iizpgi'], parent: '' },
{ name: 'cqmvs', weight: 14, children: [ 'bntzksk', 'mvpqv', 'pthnz', 'xinxep', 'qnhvjec', 'znztzxd', 'silwwua'], parent: '' },
{ name: 'wazlg', weight: 92, children: [], parent: '' },
{ name: 'unpdcwm', weight: 153, children: [ 'yktye', 'sklld', 'tdrdq'], parent: '' },
{ name: 'uknqlj', weight: 92, children: [], parent: '' },
{ name: 'qwror', weight: 369, children: [], parent: '' },
{ name: 'awxygg', weight: 89, children: [], parent: '' },
{ name: 'uwrcgnq', weight: 1176, children: [ 'uybuil', 'vqrrii', 'arejh'], parent: '' },
{ name: 'nvrpd', weight: 83, children: [], parent: '' },
{ name: 'znuldtj', weight: 30, children: [], parent: '' },
{ name: 'wxyaqte', weight: 27, children: [], parent: '' },
{ name: 'xbywgft', weight: 55, children: [], parent: '' },
{ name: 'iwidsj', weight: 95, children: [], parent: '' },
{ name: 'kcxllz', weight: 43, children: [ 'mdlubuq', 'dhecgkl', 'uvpwrf'], parent: '' },
{ name: 'arejh', weight: 188, children: [ 'lbkrk', 'jxhhc'], parent: '' },
{ name: 'qbaig', weight: 84, children: [], parent: '' },
{ name: 'mvpqv', weight: 5522, children: [ 'ojnxwzq', 'qlchz', 'awyhreh', 'ikyzq'], parent: '' },
{ name: 'lpfahc', weight: 97, children: [], parent: '' },
{ name: 'fadkfic', weight: 36, children: [], parent: '' },
{ name: 'xvwgxm', weight: 63, children: [ 'wazlg', 'vmkfcpw'], parent: '' },
{ name: 'tewltq', weight: 4134, children: [ 'cviwy', 'wknmdh', 'bcnqhw', 'vmkib', 'ezaobs', 'gewlsr', 'yevywe'], parent: '' },
{ name: 'rfwgt', weight: 78, children: [], parent: '' },
{ name: 'wsjizsy', weight: 33, children: [ 'bsiwtqq', 'uzprj', 'mwvbcqg'], parent: '' },
{ name: 'rbbkdj', weight: 191, children: [ 'rjqjwjy', 'egrit'], parent: '' },
{ name: 'cwwwcge', weight: 20, children: [], parent: '' },
{ name: 'ejbtu', weight: 58, children: [ 'qnepf', 'dsuchz'], parent: '' },
{ name: 'hefjuue', weight: 24, children: [], parent: '' },
{ name: 'coxpxpj', weight: 5, children: [ 'cbgnzhz', 'uofuvf'], parent: '' },
{ name: 'nhcmgrr', weight: 17, children: [], parent: '' },
{ name: 'iktev', weight: 194, children: [ 'chcnreg', 'olnfe'], parent: '' },
{ name: 'vhnnnv', weight: 79, children: [], parent: '' },
{ name: 'kmwkft', weight: 88, children: [ 'edfxg', 'xaovjvs'], parent: '' },
{ name: 'kdqctmq', weight: 7, children: [], parent: '' },
{ name: 'slntf', weight: 309, children: [ 'dmxlfzb', 'phdeae', 'vfdulx', 'bzorz', 'nogoyp'], parent: '' },
{ name: 'ohqivu', weight: 82, children: [ 'yjmjnm', 'taxky'], parent: '' },
{ name: 'lqasevp', weight: 26, children: [], parent: '' },
{ name: 'roojn', weight: 57, children: [], parent: '' },
{ name: 'ojrixty', weight: 97, children: [], parent: '' },
{ name: 'xmjpazn', weight: 5, children: [], parent: '' },
{ name: 'salxel', weight: 5, children: [], parent: '' },
{ name: 'lhlgijf', weight: 54, children: [], parent: '' },
{ name: 'zatfti', weight: 60, children: [ 'phkzo', 'ghqixh', 'rulju', 'ksnxlcl', 'isispf'], parent: '' },
{ name: 'znmav', weight: 95, children: [ 'byvwheg', 'kefudoj'], parent: '' },
{ name: 'myzut', weight: 91, children: [], parent: '' },
{ name: 'cekchxh', weight: 59, children: [ 'lcwqdxx', 'nkdbmjv', 'pfekvok'], parent: '' },
{ name: 'ukbzl', weight: 14, children: [], parent: '' },
{ name: 'bwrpc', weight: 41, children: [ 'jzbnq', 'fezoyaj', 'birtjxh', 'fcjjqev'], parent: '' },
{ name: 'ytadaxm', weight: 26, children: [ 'nlkwsrn', 'qtcnfy'], parent: '' },
{ name: 'qlryl', weight: 10, children: [], parent: '' },
{ name: 'vytlfm', weight: 33, children: [], parent: '' },
{ name: 'jswxshd', weight: 127, children: [ 'teapi', 'ugssydn'], parent: '' },
{ name: 'emqwt', weight: 50, children: [], parent: '' },
{ name: 'ugssydn', weight: 35, children: [], parent: '' },
{ name: 'iumsmx', weight: 20, children: [], parent: '' },
{ name: 'kigpl', weight: 89, children: [], parent: '' },
{ name: 'cdfij', weight: 68, children: [], parent: '' },
{ name: 'esmbu', weight: 8, children: [], parent: '' },
{ name: 'izpta', weight: 84, children: [], parent: '' },
{ name: 'jviven', weight: 416, children: [ 'gujegtc', 'owtswi', 'haayebg', 'yjcevge', 'mgoym', 'iqckb', 'gkqxb'], parent: '' },
{ name: 'qhiav', weight: 99, children: [], parent: '' },
{ name: 'ixoas', weight: 5, children: [], parent: '' },
{ name: 'dmxlfzb', weight: 16, children: [ 'afqwh', 'klexq', 'tiyvea'], parent: '' },
{ name: 'redeub', weight: 57, children: [ 'hxhguzh', 'vkmxs'], parent: '' },
{ name: 'fymyi', weight: 35, children: [], parent: '' },
{ name: 'mdcxis', weight: 39, children: [], parent: '' },
{ name: 'lcjjc', weight: 70, children: [], parent: '' },
{ name: 'acfnchg', weight: 246, children: [ 'advjges', 'cftggo'], parent: '' },
{ name: 'ldkojcj', weight: 8, children: [], parent: '' },
{ name: 'nwlkk', weight: 84, children: [], parent: '' },
{ name: 'kzocw', weight: 2306, children: [ 'umsrz', 'mbzzt', 'uilvahq'], parent: '' },
{ name: 'meqla', weight: 86, children: [], parent: '' },
{ name: 'drwwnwd', weight: 139, children: [ 'vrhltmp', 'njaig'], parent: '' },
{ name: 'vspquqe', weight: 79, children: [], parent: '' },
{ name: 'uymdj', weight: 76, children: [], parent: '' },
{ name: 'eutun', weight: 192, children: [ 'iumsmx', 'snsyzbk', 'wkxyxtf'], parent: '' },
{ name: 'ezaobs', weight: 434, children: [ 'lngdxkd', 'brmvw', 'hdvcgn', 'ufdbsy', 'qsxqwub', 'rkswk'], parent: '' },
{ name: 'iljkad', weight: 14, children: [], parent: '' },
{ name: 'ryeiot', weight: 41, children: [], parent: '' },
{ name: 'mwhraq', weight: 86, children: [ 'lwysj', 'lmgxknk'], parent: '' },
{ name: 'fjkfpm', weight: 69, children: [ 'kohxzh', 'liwvq', 'eqkio', 'xvoyybs'], parent: '' }
]

// matchMaker function: assign a parent to one child
function matchMaker(thisChild, thisParent) {
  var i;
  for (i=0; i<list.length; i++) {
    if (list[i].name === thisChild) {
      list[i].parent = thisParent
      return;
    }
  }
  console.log("No node", thisChild, "found");
}

// traverse the tree, assigning a parent to each node that is listed as a child

var i;
for (i=0; i<list.length; i++) {
  var j;
  for (j=0; j<list[i].children.length; j++) {
    matchMaker(list[i].children[j],list[i].name);
  }
}

// at this point we should have all parents assigned
// the root is the node with no parents: find and display it

for (i=0; i<list.length; i++) {
  if (list[i].parent === '') {
    console.dir(list[i]);
  }
}
